from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from services.proposal_quality_service import ProposalQualityService
from models.validation_evidence import ValidationEvidence


class RequirementEvidence(BaseModel):
    evidence_type: Literal["implementation", "test", "validation"]
    file_path: str | None = None
    line_start: int | None = None
    line_end: int | None = None
    description: str


class RequirementTrace(BaseModel):
    requirement_id: str
    requirement_text: str
    implementation_evidence: list[RequirementEvidence] = Field(default_factory=list)
    test_evidence: list[RequirementEvidence] = Field(default_factory=list)
    validation_evidence: list[ValidationEvidence] = Field(default_factory=list)
    status: Literal["traced", "incomplete"] = "incomplete"


class RequirementTraceViolation(BaseModel):
    code: str
    message: str
    requirement_id: str | None = None
    expected: str | None = None
    actual: str | None = None
    instruction: str | None = None


class RequirementTraceResult(BaseModel):
    status: Literal["pass", "fail"]
    traces: list[RequirementTrace] = Field(default_factory=list)
    violations: list[RequirementTraceViolation] = Field(default_factory=list)

    @property
    def passed(self) -> bool:
        return self.status == "pass"


class RequirementTraceService:
    """Builds and validates deterministic evidence links for success criteria."""

    def __init__(self) -> None:
        self._quality_helper = ProposalQualityService(".")

    def build_traces(
        self,
        *,
        proposal: dict[str, Any],
        success_criteria: list[str] | None = None,
        validation_summary: dict[str, Any] | None = None,
    ) -> list[RequirementTrace]:
        traces: list[RequirementTrace] = []
        changes = [change for change in proposal.get("changes", []) if isinstance(change, dict)]

        for index, criterion in enumerate(success_criteria or [], start=1):
            trace = RequirementTrace(
                requirement_id=f"REQ-{index:03d}",
                requirement_text=criterion,
            )
            literals = self._quality_helper._extract_required_literals([criterion])
            search_terms = sorted(literals) or [criterion]

            for change in changes:
                path = change.get("path")
                content = change.get("content")
                if not isinstance(path, str) or not isinstance(content, str):
                    continue

                # Requirement text often contains path-oriented acceptance
                # criteria generated by Planner, for example
                # "Authorized target file exists in proposal: utils/foo.py".
                # Treat create_file and replace_file changes as deterministic
                # evidence for those file-existence criteria instead of relying
                # only on quoted literals being present in file content.
                if path in criterion:
                    self._append_change_evidence(
                        trace=trace,
                        path=path,
                        line_no=1,
                        description=f"Proposed {change.get('operation', 'change')} satisfies referenced path: {path}",
                    )

                for term in search_terms:
                    line_no = self._find_line(content, term)
                    if line_no is None:
                        continue
                    self._append_change_evidence(
                        trace=trace,
                        path=path,
                        line_no=line_no,
                        description=f"Contains evidence for requirement term: {term}",
                    )

            self._add_fallback_evidence_for_generated_criteria(
                trace=trace,
                criterion=criterion,
                changes=changes,
            )

            expected_kinds = self._expected_evidence_kinds(criterion, changes)
            trace.status = "traced" if self._trace_has_expected_evidence(trace, expected_kinds) else "incomplete"
            traces.append(trace)

        return traces

    def validate(
        self,
        *,
        proposal: dict[str, Any],
        success_criteria: list[str] | None = None,
        validation_summary: dict[str, Any] | None = None,
        require_test_evidence: bool = True,
    ) -> RequirementTraceResult:
        traces = self.build_traces(
            proposal=proposal,
            success_criteria=success_criteria,
            validation_summary=validation_summary,
        )
        violations: list[RequirementTraceViolation] = []

        changes = [change for change in proposal.get("changes", []) if isinstance(change, dict)]
        for trace in traces:
            expected_kinds = self._expected_evidence_kinds(trace.requirement_text, changes)
            if "implementation" in expected_kinds and not trace.implementation_evidence:
                violations.append(
                    RequirementTraceViolation(
                        code="MISSING_IMPLEMENTATION_EVIDENCE",
                        message="Requirement has no implementation evidence.",
                        requirement_id=trace.requirement_id,
                        expected=trace.requirement_text,
                        actual="<missing>",
                        instruction="Reference a changed implementation file that demonstrates this requirement.",
                    )
                )
            if require_test_evidence and "test" in expected_kinds and not trace.test_evidence:
                violations.append(
                    RequirementTraceViolation(
                        code="MISSING_TEST_EVIDENCE",
                        message="Requirement has no test evidence.",
                        requirement_id=trace.requirement_id,
                        expected=trace.requirement_text,
                        actual="<missing>",
                        instruction="Add or update a test that asserts the requested behavior.",
                    )
                )

        return RequirementTraceResult(
            status="fail" if violations else "pass",
            traces=traces,
            violations=violations,
        )

    def summarize(self, result: RequirementTraceResult) -> dict[str, Any]:
        return {
            "status": result.status,
            "requirements": len(result.traces),
            "traced": sum(1 for trace in result.traces if trace.status == "traced"),
            "missing": len(result.violations),
            "traces": [trace.model_dump() for trace in result.traces],
            "violations": [violation.model_dump() for violation in result.violations],
        }

    def _append_change_evidence(
        self,
        *,
        trace: RequirementTrace,
        path: str,
        line_no: int,
        description: str,
    ) -> None:
        evidence = RequirementEvidence(
            evidence_type="test" if self._is_test_path(path) else "implementation",
            file_path=path,
            line_start=line_no,
            line_end=line_no,
            description=description,
        )
        target = trace.test_evidence if evidence.evidence_type == "test" else trace.implementation_evidence
        if not any(existing.file_path == evidence.file_path and existing.line_start == evidence.line_start for existing in target):
            target.append(evidence)

    def _add_fallback_evidence_for_generated_criteria(
        self,
        *,
        trace: RequirementTrace,
        criterion: str,
        changes: list[dict[str, Any]],
    ) -> None:
        lowered = criterion.lower()
        if "generated test command passes" in lowered or "executable test target" in lowered:
            for change in changes:
                path = change.get("path")
                if isinstance(path, str) and self._is_test_path(path):
                    self._append_change_evidence(
                        trace=trace,
                        path=path,
                        line_no=1,
                        description="Generated test acceptance criterion maps to proposed test file.",
                    )

        if "requirement trace covers" in lowered:
            for change in changes:
                path = change.get("path")
                if isinstance(path, str):
                    self._append_change_evidence(
                        trace=trace,
                        path=path,
                        line_no=1,
                        description="Meta trace acceptance criterion maps to proposed change evidence.",
                    )

        if "test" in lowered and not trace.test_evidence:
            for change in changes:
                path = change.get("path")
                if isinstance(path, str) and self._is_test_path(path):
                    self._append_change_evidence(
                        trace=trace,
                        path=path,
                        line_no=1,
                        description="Test-oriented acceptance criterion maps to proposed test file.",
                    )

        if "implementation" in lowered and not trace.implementation_evidence:
            for change in changes:
                path = change.get("path")
                if isinstance(path, str) and not self._is_test_path(path):
                    self._append_change_evidence(
                        trace=trace,
                        path=path,
                        line_no=1,
                        description="Implementation-oriented acceptance criterion maps to proposed implementation file.",
                    )

    def _expected_evidence_kinds(
        self,
        criterion: str,
        changes: list[dict[str, Any]],
    ) -> set[str]:
        lowered = criterion.lower()
        referenced_paths = [
            change.get("path")
            for change in changes
            if isinstance(change.get("path"), str) and change.get("path") in criterion
        ]
        if referenced_paths:
            return {"test" if self._is_test_path(path) else "implementation" for path in referenced_paths}
        if "executable test target" in lowered or "generated test command passes" in lowered:
            return {"test"}
        if "requirement trace covers" in lowered:
            kinds = {"test" if self._is_test_path(change.get("path", "")) else "implementation" for change in changes if isinstance(change.get("path"), str)}
            return kinds or {"implementation", "test"}
        if "test" in lowered and "implementation" not in lowered:
            return {"test"}
        if "implementation" in lowered and "test" not in lowered:
            return {"implementation"}
        return {"implementation", "test"}

    def _trace_has_expected_evidence(self, trace: RequirementTrace, expected_kinds: set[str]) -> bool:
        if "implementation" in expected_kinds and not trace.implementation_evidence:
            return False
        if "test" in expected_kinds and not trace.test_evidence:
            return False
        return True

    def _find_line(self, content: str, term: str) -> int | None:
        for index, line in enumerate(content.splitlines(), start=1):
            if term in line:
                return index
        return None

    def _is_test_path(self, path: str) -> bool:
        normalized = path.replace("\\", "/")
        return normalized.startswith("tests/") or normalized.split("/")[-1].startswith("test_")
