from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class MCPToolDefinition:
    """Declarative public contract for a governed Ageix MCP tool."""

    name: str
    capability_id: str
    category: str
    description: str
    version: str = "1.0"
    requires_project: bool = True
    requires_auth: bool = True
    enabled: bool = True
    experimental: bool = False
    placeholder: bool = False
    placeholder_reason: str | None = None
    input_schema: dict[str, Any] = field(default_factory=dict)
    recommended_next_tools: tuple[str, ...] = ()
    related_tools: tuple[str, ...] = ()
    documentation: dict[str, Any] = field(default_factory=dict)

    def to_discovery_dict(self) -> dict[str, Any]:
        workflow = {
            "recommended_next_tools": list(self.recommended_next_tools),
            "related_tools": list(self.related_tools),
        }
        return {
            "tool_name": self.name,
            "name": self.name,
            "capability_id": self.capability_id,
            "category": self.category,
            "description": self.description,
            "version": self.version,
            "requires_project": self.requires_project,
            "requires_auth": self.requires_auth,
            "enabled": self.enabled,
            "experimental": self.experimental,
            "placeholder": self.placeholder,
            "placeholder_reason": self.placeholder_reason,
            "input_schema": self.input_schema or {"type": "object", "properties": {}, "required": []},
            "workflow": workflow,
            "recommended_next_tools": list(self.recommended_next_tools),
            "related_tools": list(self.related_tools),
            "documentation": self.documentation,
        }


def _object_schema(properties: dict[str, dict[str, Any]], required: list[str] | None = None) -> dict[str, Any]:
    return {"type": "object", "properties": properties, "required": required or []}


def _string(description: str = "", *, enum: list[str] | None = None) -> dict[str, Any]:
    payload: dict[str, Any] = {"type": "string"}
    if description:
        payload["description"] = description
    if enum:
        payload["enum"] = enum
    return payload


def _integer(description: str = "") -> dict[str, Any]:
    payload: dict[str, Any] = {"type": "integer"}
    if description:
        payload["description"] = description
    return payload


def _boolean(description: str = "") -> dict[str, Any]:
    payload: dict[str, Any] = {"type": "boolean"}
    if description:
        payload["description"] = description
    return payload


def _array(description: str = "") -> dict[str, Any]:
    payload: dict[str, Any] = {"type": "array"}
    if description:
        payload["description"] = description
    return payload


def _object(description: str = "") -> dict[str, Any]:
    payload: dict[str, Any] = {"type": "object"}
    if description:
        payload["description"] = description
    return payload

MCP_TOOL_DEFINITIONS: tuple[MCPToolDefinition, ...] = (
    MCPToolDefinition(
        name="ageix.health",
        capability_id="ageix.health",
        category="system",
        description="Return Ageix MCP/capability interface health.",
        requires_project=False,
    ),
    MCPToolDefinition(
        name="ageix.capabilities.list",
        capability_id="capabilities.list",
        category="capability",
        description="List governed Ageix capabilities and MCP tools exposed to external clients with optional filtering and pagination.",
        requires_project=False,
        input_schema=_object_schema({
            "category": _string("Optional capability/tool category filter."),
            "query": _string("Optional case-insensitive capability/tool search text."),
            "limit": _integer("Maximum rows to return."),
            "offset": _integer("Zero-based pagination offset."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.capabilities.execute",
        capability_id="capabilities.execute",
        category="capability",
        description="Execute a governed Ageix capability by capability ID.",
        input_schema=_object_schema({
            "capability_id": _string("Capability ID to execute through governed authorization."),
            "arguments": _object("Capability arguments."),
        }, ["capability_id"]),
    ),
    MCPToolDefinition(
        name="ageix.projects.current",
        capability_id="project.current",
        category="project",
        description="Return the explicitly selected current project profile.",
    ),
    MCPToolDefinition(
        name="ageix.projects.profile",
        capability_id="project.profile",
        category="project",
        description="Return a project profile by project ID.",
        input_schema=_object_schema({"project_id": _string("Explicit project ID.")}, ["project_id"]),
    ),
    MCPToolDefinition(
        name="ageix.projects.list",
        capability_id="project.list",
        category="project",
        description="List registered Ageix projects visible to the governed interface.",
        requires_project=False,
    ),
    MCPToolDefinition(
        name="ageix.proposals.submit",
        capability_id="proposal.submit",
        category="proposal",
        description="Submit a governed proposal for Chair evaluation.",
        input_schema=_object_schema({
            "objective": _string("Proposal objective for Chair evaluation."),
            "proposal_type": _string("Proposal type.", enum=["investigation", "architecture", "implementation", "research"]),
            "parent_proposal_id": _string("Optional parent proposal ID."),
            "proposal_version": _integer("Optional proposal version."),
            "linked_evidence": _array("Linked evidence IDs."),
            "linked_consultations": _array("Linked consultation IDs."),
            "required_consultations": _array("Required consultation types."),
            "conditions": _array("Proposal conditions."),
            "metadata": _object("Additional proposal metadata."),
        }, ["objective"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.consultations.submit"),
        related_tools=("ageix.proposals.get", "ageix.proposals.list"),
    ),
    MCPToolDefinition(
        name="ageix.proposals.get",
        capability_id="proposal.details",
        category="proposal",
        description="Retrieve a governed proposal by ID.",
        input_schema=_object_schema({"proposal_id": _string("Proposal ID to retrieve.")}, ["proposal_id"]),
    ),
    MCPToolDefinition(
        name="ageix.proposals.list",
        capability_id="proposal.list",
        category="proposal",
        description="List governed proposals for a project/session.",
        input_schema=_object_schema({"limit": _integer("Maximum number of proposals to return.")}),
    ),
    MCPToolDefinition(
        name="ageix.proposals.status",
        capability_id="proposal.status",
        category="proposal",
        description="Return the current status for a governed proposal.",
        input_schema=_object_schema({"proposal_id": _string("Proposal ID to check.")}, ["proposal_id"]),
        recommended_next_tools=("ageix.consultations.submit",),
    ),
    MCPToolDefinition(
        name="ageix.consultations.submit",
        capability_id="consultation.submit",
        category="consultation",
        description="Submit external consultation input for a governed proposal.",
        input_schema=_object_schema({
            "proposal_id": _string("Proposal ID receiving consultation evidence."),
            "consultation_type": _string("Consultation type."),
            "summary": _string("Summary or recommendation text."),
            "confidence": {"type": "number", "description": "Confidence from 0.0 to 1.0."},
            "disposition": _string("Consultation disposition."),
            "evidence_sufficient": {"type": "boolean"},
            "findings": _array("Findings."),
            "concerns": _array("Concerns or risks."),
            "recommendations": _array("Suggested improvements."),
            "metadata": _object("Additional consultation metadata."),
        }, ["proposal_id", "consultation_type"]),
        recommended_next_tools=("ageix.consultations.get", "ageix.proposals.status"),
        related_tools=("ageix.consultations.list",),
    ),
    MCPToolDefinition(
        name="ageix.consultations.get",
        capability_id="consultation.details",
        category="consultation",
        description="Retrieve a submitted consultation by ID.",
        input_schema=_object_schema({"consultation_id": _string("Consultation ID to retrieve.")}, ["consultation_id"]),
    ),
    MCPToolDefinition(
        name="ageix.consultations.list",
        capability_id="consultation.list",
        category="consultation",
        description="List governed consultations.",
        input_schema=_object_schema({"limit": _integer("Maximum number of consultations to return.")}),
    ),

    MCPToolDefinition(
        name="ageix.architecture.list",
        capability_id="architecture.list",
        category="architecture",
        description="List governed architecture hierarchy nodes visible to the current project.",
        input_schema=_object_schema({
            "node_type": _string("Optional architecture node type filter.", enum=["project", "domain", "component", "service"]),
            "parent_id": _string("Optional parent architecture ID filter."),
        }),
        recommended_next_tools=("ageix.architecture.details", "ageix.architecture.children"),
        related_tools=("ageix.architecture.subtree",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.details",
        capability_id="architecture.details",
        category="architecture",
        description="Retrieve one governed architecture node by architecture ID or stable path.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path, such as Ageix.MCPPlatform.ToolRegistry."),
        }),
        recommended_next_tools=("ageix.architecture.children", "ageix.architecture.subtree"),
        related_tools=("ageix.architecture.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.children",
        capability_id="architecture.children",
        category="architecture",
        description="Retrieve direct children for a governed architecture node.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "include_node": {"type": "boolean", "description": "Include the parent node payload."},
        }),
        recommended_next_tools=("ageix.architecture.details", "ageix.architecture.subtree"),
        related_tools=("ageix.architecture.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.subtree",
        capability_id="architecture.subtree",
        category="architecture",
        description="Retrieve a governed architecture hierarchy subtree from a node.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
        }),
        recommended_next_tools=("ageix.architecture.details",),
        related_tools=("ageix.architecture.children", "ageix.architecture.list"),
    ),

    MCPToolDefinition(
        name="ageix.architecture.context",
        capability_id="architecture.context",
        category="architecture",
        description="Build summary-first architecture context for a governed architecture node without repository-wide discovery.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "include_detail": {"type": "boolean", "description": "Include detailed node and approved description payloads."},
        }),
        recommended_next_tools=("ageix.architecture.details", "ageix.evidence.package.details"),
        related_tools=("ageix.architecture.children", "ageix.architecture.subtree", "ageix.decision.trace.details"),
    ),

    MCPToolDefinition(
        name="ageix.architecture.health",
        capability_id="architecture.health",
        category="architecture",
        description="Return deterministic architecture health indicators for one governed architecture node.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
        }),
        recommended_next_tools=("ageix.architecture.coverage", "ageix.architecture.context"),
        related_tools=("ageix.architecture.details", "ageix.evidence.package.summary"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.coverage",
        capability_id="architecture.coverage",
        category="architecture",
        description="Return deterministic architecture coverage metrics for a project registry baseline.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
        }, ["project_id"]),
        recommended_next_tools=("ageix.architecture.health", "ageix.architecture.list"),
        related_tools=("ageix.architecture.subtree",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.baseline.validate",
        capability_id="architecture.baseline.validate",
        category="architecture",
        description="Validate an architecture baseline using deterministic registry and health data.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
        }, ["project_id"]),
        recommended_next_tools=("ageix.architecture.coverage", "ageix.architecture.review.submit"),
        related_tools=("ageix.architecture.health",),
    ),


    MCPToolDefinition(
        name="ageix.architecture.review.submit",
        capability_id="architecture.review.submit",
        category="architecture",
        description="Submit a governed architecture review from an authorized architect MCP partner.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "summary": _string("Review summary."),
            "rationale": _string("Review rationale."),
            "no_findings": {"type": "boolean", "description": "True when the review found no concerns."},
            "metadata": _object("Additional review metadata."),
        }),
        recommended_next_tools=("ageix.architecture.finding.submit", "ageix.architecture.review.get"),
        related_tools=("ageix.architecture.review.list", "ageix.architecture.health"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.review.get",
        capability_id="architecture.review.get",
        category="architecture",
        description="Retrieve a governed architecture review by review ID.",
        input_schema=_object_schema({"review_id": _string("Architecture review ID.")}, ["review_id"]),
        related_tools=("ageix.architecture.review.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.review.list",
        capability_id="architecture.review.list",
        category="architecture",
        description="List governed architecture reviews for a project or architecture node.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "limit": _integer("Maximum reviews to return."),
        }),
        related_tools=("ageix.architecture.review.get",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.finding.submit",
        capability_id="architecture.finding.submit",
        category="architecture",
        description="Submit a structured architecture finding from an authorized architect MCP partner.",
        input_schema=_object_schema({
            "review_id": _string("Optional architecture review ID."),
            "architecture_id": _string("Single affected architecture node ID."),
            "path": _string("Single affected stable architecture path."),
            "affected_architecture_ids": _array("Affected architecture IDs or paths."),
            "severity": _string("Finding severity.", enum=["informational", "concern", "significant_concern", "critical_concern"]),
            "category": _string("Finding category.", enum=["documentation_gap", "evidence_gap", "decision_gap", "architecture_inconsistency", "architecture_staleness", "coverage_gap", "intent_miss", "requires_additional_discovery", "other"]),
            "summary": _string("Finding summary."),
            "rationale": _string("Finding rationale."),
            "other_explanation": _string("Required when category is other."),
            "metadata": _object("Additional finding metadata."),
        }, ["summary"]),
        recommended_next_tools=("ageix.architecture.challenge.submit", "ageix.architecture.review.get"),
        related_tools=("ageix.architecture.health",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.challenge.submit",
        capability_id="architecture.challenge.submit",
        category="architecture",
        description="Submit an architecture challenge with context and intent.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "finding_id": _string("Optional finding ID that prompted the challenge."),
            "challenge_summary": _string("Challenge summary."),
            "context": _string("Architectural context for the disagreement."),
            "intent": _string("Architectural intent behind the challenge."),
            "rationale": _string("Challenge rationale."),
            "proposed_direction": _string("Optional proposed direction."),
            "metadata": _object("Additional challenge metadata."),
        }, ["challenge_summary", "context", "intent"]),
        recommended_next_tools=("ageix.architecture.revision.propose", "ageix.architecture.challenge.get"),
        related_tools=("ageix.architecture.challenge.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.challenge.get",
        capability_id="architecture.challenge.get",
        category="architecture",
        description="Retrieve a governed architecture challenge by challenge ID.",
        input_schema=_object_schema({"challenge_id": _string("Architecture challenge ID.")}, ["challenge_id"]),
        related_tools=("ageix.architecture.challenge.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.challenge.list",
        capability_id="architecture.challenge.list",
        category="architecture",
        description="List governed architecture challenges for a project or architecture node.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "limit": _integer("Maximum challenges to return."),
        }),
        related_tools=("ageix.architecture.challenge.get",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.revision.propose",
        capability_id="architecture.revision.propose",
        category="architecture",
        description="Propose a governed architecture registry revision through the existing proposal system; does not mutate the registry directly.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "challenge_id": _string("Optional challenge ID."),
            "objective": _string("Revision objective for Chair governance."),
            "proposed_changes": _object("Allowed architecture-registry-only change set."),
            "metadata": _object("Additional revision proposal metadata."),
        }, ["objective", "proposed_changes"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.proposals.get"),
        related_tools=("ageix.architecture.challenge.get", "ageix.proposals.list", "ageix.architecture.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.revisions",
        capability_id="architecture.revisions",
        category="architecture",
        description="List immutable governed architecture revisions for a project or architecture node.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "limit": _integer("Maximum revisions to return."),
        }),
        recommended_next_tools=("ageix.architecture.revision.details", "ageix.architecture.baseline.current"),
        related_tools=("ageix.architecture.history",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.revision.details",
        capability_id="architecture.revision.details",
        category="architecture",
        description="Retrieve immutable architecture revision details and optional full architecture snapshot.",
        input_schema=_object_schema({
            "revision_id": _string("Architecture revision ID."),
            "include_snapshot": {"type": "boolean", "description": "Include the immutable full architecture snapshot."},
        }, ["revision_id"]),
        related_tools=("ageix.architecture.revisions", "ageix.architecture.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.history",
        capability_id="architecture.history",
        category="architecture",
        description="Retrieve immutable architecture revision history and the current authoritative baseline.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "project_id": _string("Explicit project ID."),
        }),
        recommended_next_tools=("ageix.architecture.baseline.current", "ageix.architecture.revision.details"),
        related_tools=("ageix.architecture.revisions",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.baseline.current",
        capability_id="architecture.baseline.current",
        category="architecture",
        description="Retrieve the current authoritative architecture baseline for an architecture node.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "project_id": _string("Explicit project ID."),
            "include_snapshot": {"type": "boolean", "description": "Include the immutable full architecture snapshot."},
        }),
        related_tools=("ageix.architecture.history", "ageix.architecture.revision.details"),
    ),


    MCPToolDefinition(
        name="ageix.architecture.adr.propose",
        capability_id="architecture.adr.propose",
        category="architecture",
        description="Propose a governed Architecture Decision Record through the existing proposal system; does not directly accept or mutate ADR history.",
        input_schema=_object_schema({
            "title": _string("ADR title."),
            "context": _string("Decision context and architectural discussion background."),
            "decision": _string("Decision being proposed."),
            "rationale": _string("Rationale for the proposed decision."),
            "alternatives_considered": {"type": "array", "items": {"type": "string"}, "description": "Alternatives considered."},
            "consequences": {"type": "array", "items": {"type": "string"}, "description": "Consequences of accepting the decision."},
            "tradeoffs": {"type": "array", "items": {"type": "string"}, "description": "Tradeoffs accepted by the decision."},
            "future_considerations": {"type": "array", "items": {"type": "string"}, "description": "Future implications or backlog hints."},
            "architecture_ids": {"type": "array", "items": {"type": "string"}, "description": "Linked architecture IDs."},
            "revision_ids": {"type": "array", "items": {"type": "string"}, "description": "Linked architecture revision IDs."},
            "supersedes_adr_id": _string("Optional ADR ID superseded by this proposal."),
            "related_adr_ids": {"type": "array", "items": {"type": "string"}, "description": "Related ADR IDs."},
            "evidence_package_ids": {"type": "array", "items": {"type": "string"}, "description": "Linked evidence package IDs."},
            "metadata": _object("Additional ADR proposal metadata."),
        }, ["title", "context", "decision", "rationale"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.proposals.get"),
        related_tools=("ageix.architecture.adrs", "ageix.architecture.adr.details", "ageix.architecture.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.adrs",
        capability_id="architecture.adrs",
        category="architecture",
        description="List governed Architecture Decision Records by project, architecture, revision, or status.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "status": _string("Optional ADR status filter."),
            "limit": _integer("Maximum ADRs to return."),
        }),
        recommended_next_tools=("ageix.architecture.adr.details", "ageix.architecture.adr.history"),
        related_tools=("ageix.architecture.history",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.adr.details",
        capability_id="architecture.adr.details",
        category="architecture",
        description="Retrieve one governed Architecture Decision Record.",
        input_schema=_object_schema({"adr_id": _string("Architecture Decision Record ID.")}, ["adr_id"]),
        related_tools=("ageix.architecture.adrs", "ageix.architecture.adr.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.adr.history",
        capability_id="architecture.adr.history",
        category="architecture",
        description="Retrieve immutable Architecture Decision Record supersession history.",
        input_schema=_object_schema({"adr_id": _string("Architecture Decision Record ID.")}, ["adr_id"]),
        related_tools=("ageix.architecture.adrs", "ageix.architecture.adr.details"),
    ),

    MCPToolDefinition(
        name="ageix.workflow.current",
        capability_id="workflow.current",
        category="workflow",
        description="Return advisory workflow/session state for the current governed MCP session.",
        input_schema=_object_schema({}),
        recommended_next_tools=("ageix.proposals.submit", "ageix.consultations.submit", "ageix.proposals.status"),
    ),
    MCPToolDefinition(
        name="ageix.identity.current",
        capability_id="identity.current",
        category="identity",
        description="Return resolved MCP caller identity and governance profile for the current request context.",
        requires_project=True,
        input_schema=_object_schema({}),
        related_tools=("ageix.workflow.current",),
    ),
    MCPToolDefinition(
        name="ageix.audit.recent",
        capability_id="audit.recent",
        category="audit",
        description="Return recent scoped audit records.",
        input_schema=_object_schema({"limit": _integer("Maximum number of audit records to return.")}),
    ),
    MCPToolDefinition(
        name="ageix.governance.status",
        capability_id="governance.status",
        category="governance",
        description="Return active external-agent governance boundaries and operating constraints.",
        input_schema=_object_schema({}),
        related_tools=("ageix.identity.current", "ageix.workflow.current", "ageix.audit.recent"),
        documentation={
            "use_when": ["Understand current governance boundaries before choosing write, evidence, patch, or validation workflows."],
            "authority": "Read-only; does not grant additional authority.",
            "intent_tags": ["governance", "trust_boundary", "capability_selection"],
        },
    ),
    MCPToolDefinition(
        name="ageix.agent.list",
        capability_id="agent.list",
        category="agent",
        description="List human-managed external agent profiles and reputation levels.",
        input_schema=_object_schema({}),
        related_tools=("ageix.agent.profile", "ageix.identity.current"),
        documentation={
            "use_when": ["Understand which external agents are known to Ageix and how reputation may affect evidence budgets or access."],
            "authority": "Read-only.",
            "intent_tags": ["agent_profile", "reputation", "trust"],
        },
    ),
    MCPToolDefinition(
        name="ageix.agent.profile",
        capability_id="agent.profile",
        category="agent",
        description="Return a human-managed external agent reputation profile.",
        input_schema=_object_schema({"agent_id": _string("External agent ID.")}, ["agent_id"]),
        related_tools=("ageix.agent.list", "ageix.identity.current"),
        documentation={
            "use_when": ["Inspect agent-specific trust, reputation, or access metadata before requesting larger evidence packages."],
            "authority": "Read-only.",
            "intent_tags": ["agent_profile", "reputation", "trust"],
        },
    ),
    MCPToolDefinition(
        name="ageix.evidence.request",
        capability_id="evidence.request",
        category="evidence",
        description="Request scoped repository evidence through a Chair-governed evidence access proposal.",
        input_schema=_object_schema({
            "objective": _string("Specific evidence objective."),
            "reason": _string("Governance rationale for the evidence request."),
            "requested_evidence": {
                "type": "array",
                "description": "Requested evidence items. Supported item types include file, section, symbol, line_range, and directory_summary.",
            },
        }, ["objective", "reason"]),
        recommended_next_tools=("ageix.evidence.package.details", "ageix.evidence.package.retrieve", "ageix.evidence.package.freshness"),
        related_tools=("ageix.evidence.package.search", "ageix.evidence.package.recommend", "ageix.architecture.context"),
        documentation={
            "use_when": ["Inspect source code, implementation details, or narrowly scoped repository content for reasoning or patch design."],
            "do_not_use_when": ["Do not use repository archives just to read one source file; evidence.request is the lower-authority path."],
            "authority": "Chair-governed read; respects agent reputation budgets and evidence hard limits.",
            "intent_tags": ["inspect_code", "read_source", "understand_implementation", "gather_evidence"],
        },
    ),
    MCPToolDefinition(
        name="ageix.evidence.proposal.submit",
        capability_id="evidence.proposal.submit",
        category="evidence",
        description="Submit a governed evidence-access proposal for Chair evaluation.",
        input_schema=_object_schema({
            "objective": _string("Evidence access objective."),
            "reason": _string("Governance rationale."),
            "requested_evidence": {"type": "array", "description": "Requested evidence items."},
        }, ["objective", "reason"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.evidence.package.details"),
        related_tools=("ageix.evidence.request", "ageix.proposals.get"),
        documentation={
            "use_when": ["Create an explicit evidence access proposal rather than directly requesting a package."],
            "authority": "Governed read proposal; does not bypass Chair.",
            "intent_tags": ["evidence_proposal", "governed_read"],
        },
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.list",
        capability_id="evidence.package.list",
        category="evidence",
        description="List project-scoped immutable evidence package summaries with pagination and filters.",
        input_schema=_object_schema({
            "limit": _integer("Maximum package summaries to return."),
            "offset": _integer("Zero-based pagination offset."),
            "proposal_id": _string("Optional proposal ID filter."),
            "evidence_plan_id": _string("Optional evidence plan ID filter."),
            "stale": {"type": "boolean", "description": "Optional stale/fresh filter."},
            "objective_contains": _string("Case-insensitive objective contains filter."),
            "context_contains": _string("Case-insensitive package context contains filter."),
            "created_before": _string("Optional ISO timestamp upper bound."),
            "created_after": _string("Optional ISO timestamp lower bound."),
        }),
        recommended_next_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness", "ageix.evidence.package.retrieve"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.search",
        capability_id="evidence.package.search",
        category="evidence",
        description="Search project-scoped immutable evidence package summaries without returning package contents.",
        input_schema=_object_schema({
            "query": _string("Search text matched against package objective/context."),
            "limit": _integer("Maximum package summaries to return."),
            "offset": _integer("Zero-based pagination offset."),
            "proposal_id": _string("Optional proposal ID filter."),
            "evidence_plan_id": _string("Optional evidence plan ID filter."),
            "stale": {"type": "boolean", "description": "Optional stale/fresh filter."},
            "objective_contains": _string("Case-insensitive objective contains filter."),
            "context_contains": _string("Case-insensitive package context contains filter."),
        }),
        recommended_next_tools=("ageix.evidence.package.details", "ageix.evidence.package.retrieve", "ageix.evidence.package.recommend"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.details",
        capability_id="evidence.package.details",
        category="evidence",
        description="Inspect package metadata, freshness, counts, and provenance manifest without returning package contents.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.retrieve", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.freshness",
        capability_id="evidence.package.freshness",
        category="evidence",
        description="Evaluate current repository content freshness for one evidence package and update the index.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.details",),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.rehydrate",
        capability_id="evidence.package.rehydrate",
        category="evidence",
        description="Legacy alias: return one immutable historical evidence package by package ID without freshness evaluation.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.retrieve",
        capability_id="evidence.package.retrieve",
        category="evidence",
        description="Retrieve immutable historical evidence package contents after an explicit package request.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.recommend",
        capability_id="evidence.package.recommend",
        category="evidence",
        description="Recommend visible historical evidence packages for a new objective; advisory to Chair only.",
        input_schema=_object_schema({
            "objective": _string("Objective to compare against visible package history."),
            "limit": _integer("Maximum recommendations to return."),
            "min_similarity": {"type": "number", "description": "Minimum deterministic similarity threshold."},
        }, ["objective"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.reuse"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.reuse",
        capability_id="evidence.package.reuse",
        category="evidence",
        description="Create a new immutable child package that records Chair-approved reuse of a visible parent package.",
        input_schema=_object_schema({
            "package_id": _string("Parent evidence package ID."),
            "objective": _string("Optional child package objective."),
            "lineage_type": _string("Lineage type.", enum=["reuse", "refresh", "expansion", "derived"]),
            "reuse_reason": _string("Chair reuse decision rationale."),
        }, ["package_id"]),
        related_tools=("ageix.evidence.package.lineage", "ageix.evidence.package.details"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.deprecate",
        capability_id="evidence.package.deprecate",
        category="evidence",
        description="Mark a visible package deprecated in catalog metadata without mutating package contents.",
        input_schema=_object_schema({
            "package_id": _string("Evidence package ID."),
            "reason": _string("Governance deprecation rationale."),
        }, ["package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.recommend"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.supersede",
        capability_id="evidence.package.supersede",
        category="evidence",
        description="Mark a visible package superseded by a newer compatible package without mutating package contents.",
        input_schema=_object_schema({
            "package_id": _string("Evidence package ID being superseded."),
            "superseded_by_package_id": _string("Newer replacement evidence package ID."),
            "reason": _string("Governance supersession rationale."),
        }, ["package_id", "superseded_by_package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.recommend"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.lineage",
        capability_id="evidence.package.lineage",
        category="evidence",
        description="Return visible parent, child, ancestor, and descendant package lineage.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.retrieve"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.create",
        capability_id="decision.trace.create",
        category="decision_trace",
        description="Internal Chair-only decision trace creation capability; not exposed as an enabled MCP tool.",
        enabled=False,
        input_schema=_object_schema({
            "decision_summary": _string("Decision summary."),
            "outcome": _string("Decision outcome.", enum=["approved", "rejected", "implemented", "superseded", "abandoned", "deferred", "backlog"]),
            "decision_id": _string("Optional external decision ID."),
            "decision_type": _string("Decision type."),
            "proposal_id": _string("Linked proposal ID."),
            "evidence_package_ids": _array("Linked evidence package IDs."),
            "consultation_ids": _array("Linked consultation IDs."),
            "validation_ids": _array("Linked validation IDs."),
            "repository_snapshot": _object("Repository snapshot metadata."),
            "reason": _string("Decision rationale."),
            "outcome_metadata": _object("Future outcome hook metadata such as backlog/deferred details."),
            "related_entities": _object("Extensible related entity IDs for future architecture links."),
            "metadata": _object("Additional trace metadata."),
        }, ["decision_summary", "outcome"]),
        related_tools=("ageix.decision.trace.get", "ageix.decision.trace.list"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.get",
        capability_id="decision.trace.get",
        category="decision_trace",
        description="Legacy alias: retrieve one append-only decision trace with linked package summaries and current freshness awareness.",
        input_schema=_object_schema({
            "trace_id": _string("Decision trace ID."),
            "include_freshness": {"type": "boolean", "description": "Include current package freshness indicators."},
        }, ["trace_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.details",
        capability_id="decision.trace.details",
        category="decision_trace",
        description="Retrieve one append-only decision trace with linked package summaries and current freshness awareness.",
        input_schema=_object_schema({
            "trace_id": _string("Decision trace ID."),
            "include_freshness": {"type": "boolean", "description": "Include current package freshness indicators."},
        }, ["trace_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.list",
        capability_id="decision.trace.list",
        category="decision_trace",
        description="List project-scoped decision traces by proposal, package, outcome, or summary text.",
        input_schema=_object_schema({
            "limit": _integer("Maximum traces to return."),
            "offset": _integer("Zero-based pagination offset."),
            "decision_id": _string("Decision ID filter."),
            "proposal_id": _string("Proposal ID filter."),
            "evidence_package_id": _string("Evidence package ID filter."),
            "outcome": _string("Outcome filter.", enum=["approved", "rejected", "implemented", "superseded", "abandoned", "deferred", "backlog"]),
            "summary_contains": _string("Case-insensitive decision summary contains filter."),
        }),
        related_tools=("ageix.decision.trace.get",),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.search",
        capability_id="decision.trace.search",
        category="decision_trace",
        description="Search project-scoped decision traces by query, proposal, package, outcome, or summary text.",
        input_schema=_object_schema({
            "query": _string("Search text matched against decision summary."),
            "limit": _integer("Maximum traces to return."),
            "offset": _integer("Zero-based pagination offset."),
            "decision_id": _string("Decision ID filter."),
            "proposal_id": _string("Proposal ID filter."),
            "evidence_package_id": _string("Evidence package ID filter."),
            "outcome": _string("Outcome filter.", enum=["approved", "rejected", "implemented", "superseded", "abandoned", "deferred", "backlog"]),
            "summary_contains": _string("Case-insensitive decision summary contains filter."),
        }),
        related_tools=("ageix.decision.trace.details",),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.history",
        capability_id="decision.trace.history",
        category="decision_trace",
        description="Find historical decision traces related to a package, proposal, or decision ID.",
        input_schema=_object_schema({
            "package_id": _string("Evidence package ID filter."),
            "proposal_id": _string("Proposal ID filter."),
            "decision_id": _string("Decision ID filter."),
            "limit": _integer("Maximum traces to return."),
            "offset": _integer("Zero-based pagination offset."),
        }),
        related_tools=("ageix.decision.trace.details", "ageix.evidence.package.details"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.package_history",
        capability_id="decision.trace.package_history",
        category="decision_trace",
        description="Legacy alias: find decision traces that used a specific evidence package.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.decision.trace.get", "ageix.evidence.package.details"),
    ),

    MCPToolDefinition(
        name="ageix.architecture.principle.propose",
        capability_id="architecture.principle.propose",
        category="architecture",
        description="Propose a governed Architecture Principle through the existing proposal system; does not directly accept or mutate guidance history.",
        input_schema=_object_schema({
            "title": _string("Principle title."),
            "statement": _string("Constraint, rule, or standard statement."),
            "rationale": _string("Principle rationale."),
            "scope": _string("Principle scope."),
            "architecture_ids": _array("Linked architecture IDs."),
            "adr_ids": _array("Linked ADR IDs."),
            "revision_ids": _array("Linked architecture revision IDs."),
            "supersedes_principle_id": _string("Optional principle ID superseded by this proposal."),
            "related_principle_ids": _array("Related principle IDs."),
            "evidence_package_ids": _array("Linked evidence package IDs."),
            "metadata": _object("Additional principle proposal metadata."),
        }, ["title", "statement"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.proposals.get"),
        related_tools=("ageix.architecture.principles", "ageix.architecture.principle.details", "ageix.architecture.guidance"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.principles",
        capability_id="architecture.principles",
        category="architecture",
        description="List governed Architecture Principles by project, architecture, ADR, revision, or status.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "adr_id": _string("Optional ADR ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "status": _string("Optional principle status filter."),
            "limit": _integer("Maximum principles to return."),
        }),
        recommended_next_tools=("ageix.architecture.principle.details", "ageix.architecture.principle.history"),
        related_tools=("ageix.architecture.guidance",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.principle.details",
        capability_id="architecture.principle.details",
        category="architecture",
        description="Retrieve one governed Architecture Principle.",
        input_schema=_object_schema({"principle_id": _string("Architecture Principle ID.")}, ["principle_id"]),
        related_tools=("ageix.architecture.principles", "ageix.architecture.principle.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.principle.history",
        capability_id="architecture.principle.history",
        category="architecture",
        description="Retrieve immutable Architecture Principle supersession history.",
        input_schema=_object_schema({"principle_id": _string("Architecture Principle ID.")}, ["principle_id"]),
        related_tools=("ageix.architecture.principles", "ageix.architecture.principle.details"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.intent.propose",
        capability_id="architecture.intent.propose",
        category="architecture",
        description="Propose governed Architecture Intent through the existing proposal system; does not directly accept or mutate guidance history.",
        input_schema=_object_schema({
            "title": _string("Intent title."),
            "summary": _string("Intent summary or directional architectural aim."),
            "details": _string("Intent details."),
            "scope": _string("Intent scope."),
            "future_considerations": _array("Future implications or backlog hints."),
            "architecture_ids": _array("Linked architecture IDs."),
            "adr_ids": _array("Linked ADR IDs."),
            "principle_ids": _array("Linked principle IDs."),
            "revision_ids": _array("Linked architecture revision IDs."),
            "supersedes_intent_id": _string("Optional intent ID superseded by this proposal."),
            "related_intent_ids": _array("Related intent IDs."),
            "evidence_package_ids": _array("Linked evidence package IDs."),
            "metadata": _object("Additional intent proposal metadata."),
        }, ["title", "summary"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.proposals.get"),
        related_tools=("ageix.architecture.intents", "ageix.architecture.intent.details", "ageix.architecture.guidance"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.intents",
        capability_id="architecture.intents",
        category="architecture",
        description="List governed Architecture Intent records by project, architecture, ADR, principle, revision, or status.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "adr_id": _string("Optional ADR ID."),
            "principle_id": _string("Optional principle ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "status": _string("Optional intent status filter."),
            "limit": _integer("Maximum intents to return."),
        }),
        recommended_next_tools=("ageix.architecture.intent.details", "ageix.architecture.intent.history"),
        related_tools=("ageix.architecture.guidance",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.intent.details",
        capability_id="architecture.intent.details",
        category="architecture",
        description="Retrieve one governed Architecture Intent record.",
        input_schema=_object_schema({"intent_id": _string("Architecture Intent ID.")}, ["intent_id"]),
        related_tools=("ageix.architecture.intents", "ageix.architecture.intent.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.intent.history",
        capability_id="architecture.intent.history",
        category="architecture",
        description="Retrieve immutable Architecture Intent supersession history.",
        input_schema=_object_schema({"intent_id": _string("Architecture Intent ID.")}, ["intent_id"]),
        related_tools=("ageix.architecture.intents", "ageix.architecture.intent.details"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.guidance",
        capability_id="architecture.guidance",
        category="architecture",
        description="Return derived architecture guidance from accepted principles and intent for an architecture node, ADR, revision, or project.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "adr_id": _string("Optional ADR ID."),
            "revision_id": _string("Optional architecture revision ID."),
        }),
        related_tools=("ageix.architecture.principles", "ageix.architecture.intents", "ageix.architecture.context"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.guidance.context",
        capability_id="architecture.guidance.context",
        category="architecture",
        description="Build or explicitly persist a summary-first Architecture Guidance Context Package.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "path": _string("Optional stable architecture path."),
            "adr_id": _string("Optional ADR ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "principle_id": _string("Optional Architecture Principle ID."),
            "intent_id": _string("Optional Architecture Intent ID."),
            "persist": {"type": "boolean", "description": "Persist immutable GUIDECTX package snapshot when true."},
        }),
        related_tools=("ageix.architecture.guidance", "ageix.architecture.context", "ageix.architecture.principles", "ageix.architecture.intents"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.guidance.context.get",
        capability_id="architecture.guidance.context.get",
        category="architecture",
        description="Retrieve a persisted Architecture Guidance Context Package by ID.",
        input_schema=_object_schema({"package_id": _string("GUIDECTX package ID.")}, ["package_id"]),
        related_tools=("ageix.architecture.guidance.context",),
    ),

    MCPToolDefinition(
        name="ageix.architecture.work.context",
        capability_id="architecture.work.context",
        category="architecture",
        description="Build or explicitly persist a summary-first Architecture Work Context Package.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "work_summary": _string("Human-readable summary of the proposed work."),
            "architecture_id": _string("Optional architecture node ID."),
            "architecture_ids": {"type": "array", "description": "Optional architecture node IDs."},
            "path": _string("Optional stable architecture path."),
            "adr_id": _string("Optional ADR ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "principle_id": _string("Optional Architecture Principle ID."),
            "intent_id": _string("Optional Architecture Intent ID."),
            "node_key": _string("Optional exact architecture node key."),
            "name": _string("Optional exact architecture node name."),
            "max_depth": _integer("Impact traversal depth. Sprint 18.9 supports 1 only."),
            "persist": {"type": "boolean", "description": "Persist immutable WORKCTX package snapshot when true."},
            "persist_guidance_context": {"type": "boolean", "description": "Persist underlying GUIDECTX snapshot when true."},
        }),
        related_tools=("ageix.architecture.guidance.context", "ageix.architecture.context", "ageix.architecture.details"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.work.context.get",
        capability_id="architecture.work.context.get",
        category="architecture",
        description="Retrieve a persisted Architecture Work Context Package by ID.",
        input_schema=_object_schema({"work_context_id": _string("WORKCTX package ID.")}, ["work_context_id"]),
        related_tools=("ageix.architecture.work.context",),
    ),

    MCPToolDefinition(
        name="ageix.validation.scenarios.list",
        capability_id="validation.scenarios.list",
        category="validation",
        description="Reserved validation sandbox scenario discovery contract.",
        experimental=True,
        placeholder=True,
        placeholder_reason="validation sandbox not yet implemented",
    ),
    MCPToolDefinition(
        name="ageix.validation.scenario.request",
        capability_id="validation.scenario.request",
        category="validation",
        description="Reserved governed validation sandbox scenario request contract.",
        experimental=True,
        placeholder=True,
        placeholder_reason="validation sandbox not yet implemented",
        input_schema=_object_schema({"scenario": _string("Validation scenario identifier.")}),
        recommended_next_tools=("ageix.validation.result.get",),
    ),
    MCPToolDefinition(
        name="ageix.validation.result.get",
        capability_id="validation.result.get",
        category="validation",
        description="Reserved governed validation sandbox result retrieval contract.",
        experimental=True,
        placeholder=True,
        placeholder_reason="validation sandbox not yet implemented",
        input_schema=_object_schema({"result_id": _string("Validation result identifier.")}, ["result_id"]),
    ),
    MCPToolDefinition(
        name="ageix.artifact.list",
        capability_id="artifact.list",
        category="artifact",
        description="List governed artifacts with pagination and filters.",
        input_schema=_object_schema({
            "artifact_category": _string("Optional artifact category filter."),
            "artifact_type": _string("Optional artifact type filter."),
            "source_id": _string("Optional source ID filter, such as validation run or archive ID."),
            "created_by": _string("Optional producer capability filter."),
            "limit": _integer("Maximum artifacts to return."),
            "offset": _integer("Zero-based artifact offset."),
        }),
        recommended_next_tools=("ageix.artifact.metadata", "ageix.artifact.get"),
    ),
    MCPToolDefinition(
        name="ageix.artifact.get",
        capability_id="artifact.get",
        category="artifact",
        description="Retrieve one governed artifact registry record.",
        input_schema=_object_schema({"artifact_id": _string("Artifact ID.")}, ["artifact_id"]),
    ),
    MCPToolDefinition(
        name="ageix.artifact.metadata",
        capability_id="artifact.metadata",
        category="artifact",
        description="Retrieve summary-first artifact metadata and relationships.",
        input_schema=_object_schema({"artifact_id": _string("Artifact ID.")}, ["artifact_id"]),
        related_tools=("ageix.artifact.get",),
    ),

    MCPToolDefinition(
        name="ageix.patch.create",
        capability_id="patch.create",
        category="patch",
        description="Store unified diff text as a governed patch artifact without applying it. Prefer ageix.patch.ingest for large patch files.",
        input_schema=_object_schema({
            "patch_name": _string("Patch file name."),
            "patch_content": _string("Unified diff patch content, limited to 1 MB."),
            "summary": _string("Patch summary."),
            "metadata": _object("Additional patch metadata."),
        }, ["patch_content"]),
        recommended_next_tools=("ageix.patch.validate", "ageix.patch.metadata", "ageix.artifact.metadata"),
        related_tools=("ageix.patch.ingest",),
    ),
    MCPToolDefinition(
        name="ageix.patch.ingest",
        capability_id="patch.ingest",
        category="patch",
        description="Import a server-local patch file as a governed patch artifact without transporting large patch text through JSON.",
        input_schema=_object_schema({
            "source_path": _string("Repo-relative path to the patch file under .ageix/artifact_deliveries/local_export or .ageix/patch_imports."),
            "patch_name": _string("Optional patch file name."),
            "summary": _string("Patch summary."),
            "metadata": _object("Additional patch metadata."),
        }, ["source_path"]),
        recommended_next_tools=("ageix.patch.metadata", "ageix.patch.get"),
        related_tools=("ageix.patch.create", "ageix.artifact.delivery.get"),
        documentation={
            "use_when": ["Import a generated patch file that already exists on the Ageix server, avoiding large JSON patch payloads."],
            "do_not_use_when": ["Do not use for arbitrary file reads; source_path is restricted to approved Ageix import/export locations."],
            "consumes": ["patch file"],
            "produces": ["PATCH-*", "ART-*"],
            "intent_tags": ["import_patch", "file_transport", "avoid_large_json_payload"],
        },
    ),
    MCPToolDefinition(
        name="ageix.patch.list",
        capability_id="patch.list",
        category="patch",
        description="List governed patch packages.",
        input_schema=_object_schema({
            "status": _string("Optional patch status filter."),
            "validation_status": _string("Optional validation status filter."),
            "limit": _integer("Maximum patches to return."),
            "offset": _integer("Zero-based patch offset."),
        }),
        recommended_next_tools=("ageix.patch.metadata", "ageix.patch.get"),
    ),
    MCPToolDefinition(
        name="ageix.patch.get",
        capability_id="patch.get",
        category="patch",
        description="Retrieve governed patch package metadata and optionally patch content.",
        input_schema=_object_schema({
            "patch_id": _string("Patch package ID."),
            "include_content": _boolean("Include patch content when true."),
        }, ["patch_id"]),
        related_tools=("ageix.patch.metadata",),
    ),
    MCPToolDefinition(
        name="ageix.patch.metadata",
        capability_id="patch.metadata",
        category="patch",
        description="Retrieve summary-first governed patch metadata.",
        input_schema=_object_schema({"patch_id": _string("Patch package ID.")}, ["patch_id"]),
        recommended_next_tools=("ageix.patch.validate",),
        related_tools=("ageix.patch.get", "ageix.patch.validation.list"),
        documentation={
            "use_when": ["Inspect patch status, validation status, artifact ID, and metadata before validation or apply workflows."],
            "authority": "Read-only.",
            "intent_tags": ["patch_metadata", "patch_quality_gate"],
        },
    ),
    MCPToolDefinition(
        name="ageix.patch.validate",
        capability_id="patch.validate",
        category="patch",
        description="Validate a stored patch artifact with git apply --check only; does not apply the patch or mutate the repository.",
        input_schema=_object_schema({"patch_id": _string("Stored PATCH-* package ID to validate.")}, ["patch_id"]),
        recommended_next_tools=("ageix.patch.validation.get", "ageix.patch.validation.list"),
        related_tools=("ageix.patch.metadata", "ageix.patch.get"),
        documentation={
            "use_when": ["Check whether a stored patch can apply cleanly before giving apply instructions or using a future apply worker."],
            "do_not_use_when": ["Do not use for test execution, repository mutation, patch apply, branch changes, or commits."],
            "consumes": ["PATCH-*"],
            "produces": ["PATCHVAL-*"],
            "intent_tags": ["validate_patch", "quality_gate", "no_mutation"],
        },
    ),
    MCPToolDefinition(
        name="ageix.patch.validation.get",
        capability_id="patch.validation.get",
        category="patch",
        description="Retrieve one stored patch validation result by PATCHVAL-* ID.",
        input_schema=_object_schema({"patch_validation_id": _string("Patch validation result ID.")}, ["patch_validation_id"]),
        related_tools=("ageix.patch.validation.list", "ageix.patch.metadata"),
        documentation={
            "use_when": ["Inspect a specific patch validation result including status and stdout/stderr tails."],
            "authority": "Read-only.",
        },
    ),
    MCPToolDefinition(
        name="ageix.patch.validation.list",
        capability_id="patch.validation.list",
        category="patch",
        description="List stored patch validation history with optional patch ID and status filters.",
        input_schema=_object_schema({
            "patch_id": _string("Optional PATCH-* package ID filter."),
            "status": _string("Optional validation status filter.", enum=["passed", "failed", "error"]),
            "limit": _integer("Maximum validations to return."),
            "offset": _integer("Zero-based validation offset."),
        }),
        recommended_next_tools=("ageix.patch.validation.get",),
        related_tools=("ageix.patch.metadata", "ageix.patch.validate"),
        documentation={
            "use_when": ["Determine whether a patch has a recent passed validation before apply workflows."],
            "authority": "Read-only.",
            "intent_tags": ["validation_history", "patch_quality_gate"],
        },
    ),

    MCPToolDefinition(
        name="ageix.artifact.push",
        capability_id="artifact.push",
        category="artifact_delivery",
        description="Deliver an existing governed artifact to an approved destination or the authenticated requesting agent.",
        input_schema=_object_schema({
            "artifact_id": _string("Artifact ID to deliver."),
            "destination": _string("Approved delivery destination. Defaults to authenticated requesting agent.", enum=["requesting_agent", "local_export"]),
        }, ["artifact_id"]),
        recommended_next_tools=("ageix.artifact.delivery.get", "ageix.artifact.delivery.list"),
        related_tools=("ageix.artifact.metadata", "ageix.artifact.get"),
        documentation={
            "use_when": ["Deliver a governed artifact to an approved destination after creating an archive, patch, validation result, or other artifact."],
            "do_not_use_when": ["Do not use to inspect source code; use evidence.request for source inspection."],
            "intent_tags": ["transport_artifact", "deliver_to_requesting_agent"],
        },
    ),
    MCPToolDefinition(
        name="ageix.artifact.delivery.get",
        capability_id="artifact.delivery.get",
        category="artifact_delivery",
        description="Retrieve one artifact delivery record.",
        input_schema=_object_schema({
            "delivery_id": _string("Artifact delivery ID."),
            "include_reference": _boolean("Explicitly include internal delivery reference details when true."),
        }, ["delivery_id"]),
    ),
    MCPToolDefinition(
        name="ageix.artifact.delivery.list",
        capability_id="artifact.delivery.list",
        category="artifact_delivery",
        description="List artifact delivery records with pagination and filters.",
        input_schema=_object_schema({
            "artifact_id": _string("Optional artifact ID filter."),
            "destination": _string("Optional destination filter."),
            "status": _string("Optional delivery status filter."),
            "limit": _integer("Maximum deliveries to return."),
            "offset": _integer("Zero-based delivery offset."),
        }),
    ),

    MCPToolDefinition(
        name="ageix.repo.info",
        capability_id="repo.info",
        category="repository",
        description="Return summary-first repository identity and git availability.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.status",
        capability_id="repo.status",
        category="repository",
        description="Return summary-first repository status and cleanliness.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.branch.current",
        capability_id="repo.branch.current",
        category="repository",
        description="Return the active repository branch.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.branch.list",
        capability_id="repo.branch.list",
        category="repository",
        description="List local repository branches with summaries.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.history",
        capability_id="repo.history",
        category="repository",
        description="Return paginated recent commit summaries.",
        input_schema=_object_schema({
            "limit": _integer("Maximum commits to return."),
            "offset": _integer("Zero-based commit offset."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.repo.diff.summary",
        capability_id="repo.diff.summary",
        category="repository",
        description="Return changed-file and shortstat summaries without full diffs.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.archive.create",
        capability_id="repo.archive.create",
        category="repository",
        description="Create a governed repository archive for selected paths or the whole repo with static exclusions.",
        input_schema=_object_schema({
            "paths": _array("Optional repo-relative paths to include. Omit for whole-repo snapshot."),
            "archive_name": _string("Optional archive file name."),
        }),
        recommended_next_tools=("ageix.artifact.push", "ageix.artifact.metadata", "ageix.artifact.delivery.get"),
        documentation={
            "use_when": ["Package selected repository paths or the whole repository as a governed artifact for transport or external review."],
            "do_not_use_when": ["Do not use when the goal is to inspect a small amount of source; prefer evidence.request for governed source inspection."],
            "produces": ["REPOARCH-*", "ART-*"],
            "intent_tags": ["package_repository", "transport_repository_context"],
        },
    ),
    MCPToolDefinition(
        name="ageix.repo.archive.list",
        capability_id="repo.archive.list",
        category="repository",
        description="List governed repository archives.",
        input_schema=_object_schema({
            "limit": _integer("Maximum archives to return."),
            "offset": _integer("Zero-based archive offset."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.validation.profile.list",
        capability_id="validation.profile.list",
        category="validation",
        description="List approved validation profiles available for governed execution.",
        input_schema=_object_schema({
            "limit": _integer("Maximum profiles to return."),
            "offset": _integer("Zero-based profile offset."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.validation.profile.get",
        capability_id="validation.profile.get",
        category="validation",
        description="Get an approved validation profile by ID.",
        input_schema=_object_schema({"profile_id": _string("Validation profile ID.")}, ["profile_id"]),
    ),
    MCPToolDefinition(
        name="ageix.validation.run.start",
        capability_id="validation.run.start",
        category="validation",
        description="Start an approved validation profile asynchronously. No arbitrary command input is accepted.",
        input_schema=_object_schema({"profile_id": _string("Validation profile ID to execute.")}, ["profile_id"]),
        recommended_next_tools=("ageix.validation.run.status", "ageix.validation.run.result"),
    ),
    MCPToolDefinition(
        name="ageix.validation.run.status",
        capability_id="validation.run.status",
        category="validation",
        description="Return summary-first status for an asynchronous validation run.",
        input_schema=_object_schema({"run_id": _string("Validation run ID.")}, ["run_id"]),
        recommended_next_tools=("ageix.validation.run.result",),
    ),
    MCPToolDefinition(
        name="ageix.validation.run.result",
        capability_id="validation.run.result",
        category="validation",
        description="Return validation run result, evidence package ID, and truncated output tails.",
        input_schema=_object_schema({"run_id": _string("Validation run ID.")}, ["run_id"]),
    ),
    MCPToolDefinition(
        name="ageix.validation.history",
        capability_id="validation.history",
        category="validation",
        description="List historical validation runs summary-first.",
        input_schema=_object_schema({
            "limit": _integer("Maximum runs to return."),
            "offset": _integer("Zero-based run offset."),
        }),
    ),

    MCPToolDefinition(
        name="ageix.conversation.open",
        capability_id="conversation.open",
        category="conversation",
        description="Open a governed shared conversation with a declared set of participants, per ADR-0016.",
        input_schema=_object_schema({
            "participants": _array("Participants to register: list of {client_id, agent_role, session_id}."),
            "project_id": _string("Optional project ID to scope the conversation to."),
            "metadata": _object("Optional free-form conversation metadata."),
        }, ["participants"]),
        recommended_next_tools=("ageix.conversation.turn.append", "ageix.conversation.get"),
    ),
    MCPToolDefinition(
        name="ageix.conversation.transition",
        capability_id="conversation.transition",
        category="conversation",
        description="Transition a shared conversation's lifecycle state, per ADR-0016's state machine.",
        input_schema=_object_schema({
            "conversation_id": _string("Conversation ID to transition."),
            "new_state": _string(
                "Target conversation state.",
                enum=["OPEN", "ACTIVE", "WAITING_FOR_GREG", "WAITING_FOR_AGENT", "CONVERGED", "ESCALATED", "CLOSED", "ARCHIVED"],
            ),
        }, ["conversation_id", "new_state"]),
    ),
    MCPToolDefinition(
        name="ageix.conversation.get",
        capability_id="conversation.get",
        category="conversation",
        description="Retrieve a shared conversation's state, participants, rules of engagement, and recent turns.",
        input_schema=_object_schema({
            "conversation_id": _string("Conversation ID to retrieve."),
            "recent_turn_limit": _integer("Maximum number of most-recent turns to include."),
        }, ["conversation_id"]),
        recommended_next_tools=("ageix.conversation.turn.list", "ageix.conversation.participant.list"),
    ),
    MCPToolDefinition(
        name="ageix.conversation.turn.append",
        capability_id="conversation.turn.append",
        category="conversation",
        description="Append an immutable turn to a shared conversation as the authenticated caller, per ADR-0016.",
        input_schema=_object_schema({
            "conversation_id": _string("Conversation ID to append the turn to."),
            "turn_type": _string(
                "Turn classification.",
                enum=["STATEMENT", "QUESTION", "ANSWER", "DIRECTIVE", "SPECULATION", "OBSERVATION", "NO_COMMENT", "ABSTAIN", "ESCALATE"],
            ),
            "content": _string("Turn content."),
            "confidence": {"type": "number", "description": "Confidence from 0.0 to 10.0."},
            "directed_at": _string("Optional agent_role this turn directs a question to."),
            "model_id": _string("Underlying model identifier that produced this turn."),
        }, ["conversation_id", "turn_type", "content", "confidence"]),
        recommended_next_tools=("ageix.conversation.turn.list",),
    ),
    MCPToolDefinition(
        name="ageix.conversation.turn.list",
        capability_id="conversation.turn.list",
        category="conversation",
        description="List the append-only turn history of a shared conversation.",
        input_schema=_object_schema({
            "conversation_id": _string("Conversation ID to list turns for."),
            "limit": _integer("Maximum number of turns to return."),
            "offset": _integer("Zero-based turn offset."),
            "most_recent": _boolean("Return the most recent `limit` turns instead of the earliest."),
        }, ["conversation_id"]),
    ),
    MCPToolDefinition(
        name="ageix.conversation.participant.list",
        capability_id="conversation.participant.list",
        category="conversation",
        description="List registered participants of a shared conversation.",
        input_schema=_object_schema({"conversation_id": _string("Conversation ID to list participants for.")}, ["conversation_id"]),
    ),
    MCPToolDefinition(
        name="ageix.conversation.participant.obligations",
        capability_id="conversation.participant.obligations",
        category="conversation",
        description="List pending directed-question obligations by agent role for a shared conversation.",
        input_schema=_object_schema({"conversation_id": _string("Conversation ID to check obligations for.")}, ["conversation_id"]),
    ),
    MCPToolDefinition(
        name="ageix.conversation.handoff.create",
        capability_id="conversation.handoff.create",
        category="conversation",
        description="Serialize a governed HANDOFF_PACKAGE artifact summarizing a shared conversation, per ADR-0016.",
        input_schema=_object_schema({
            "conversation_id": _string("Conversation ID to summarize for handoff."),
            "requested_action": _string("Action requested of the handoff recipient."),
            "conversation_summary": _string("Optional human-readable conversation summary."),
            "outstanding_questions": _array("Optional list of outstanding question records."),
        }, ["conversation_id", "requested_action"]),
        recommended_next_tools=("ageix.conversation.handoff.get",),
    ),
    MCPToolDefinition(
        name="ageix.conversation.handoff.get",
        capability_id="conversation.handoff.get",
        category="conversation",
        description="Retrieve one governed HANDOFF_PACKAGE artifact by ID.",
        input_schema=_object_schema({"handoff_id": _string("Handoff ID to retrieve.")}, ["handoff_id"]),
    ),

    MCPToolDefinition(
        name="ageix.devjob.create",
        capability_id="devjob.create",
        category="devjob",
        description="Create a governed DevJob work assignment describing what should be implemented, reviewed, or investigated, per INTENT-0007. A DevJob is a coordination contract; it does not execute work.",
        input_schema=_object_schema({
            "title": _string("Short DevJob title."),
            "objective": _string("What the DevJob should achieve."),
            "instructions": _array("Ordered list of instructions for the assignee."),
            "acceptance_criteria": _array("List of criteria the result must satisfy."),
            "allowed_paths": _array("Repository paths the assignee may touch."),
            "prohibited_paths": _array("Repository paths the assignee must not touch."),
            "repo_target": _string("Target repository identifier."),
            "branch_hint": _string("Suggested branch name for the work, by reference only."),
            "evidence_package_ids": _array("Evidence package IDs relevant to this DevJob."),
            "work_context_id": _string("Related WORKCTX package ID, if any."),
            "validation_profile_ids": _array("Validation profile IDs the result should be checked against."),
            "conversation_id": _string("Related shared conversation ID, if any."),
            "handoff_id": _string("Related HANDOFF_PACKAGE ID, if any."),
            "origin": _string("How this DevJob originated, e.g. manual, conversation, handoff."),
            "status": _string("Initial DevJob status.", enum=["draft", "assigned"]),
            "created_by": _string("Explicit creator identity; defaults to the caller's client_id."),
            "assigned_to": _string("Identity of the assignee, required when status is assigned."),
        }, ["title", "objective"]),
        recommended_next_tools=("ageix.devjob.get", "ageix.devjob.list"),
        related_tools=("ageix.devjob.result.submit", "ageix.conversation.open", "ageix.conversation.handoff.create"),
        documentation={
            "use_when": ["Describe a governed unit of work for a DevWorker to implement, review, or investigate, without executing it directly."],
            "do_not_use_when": ["Do not use this to perform git operations, generate patches, or run validation directly — DevJob is a coordination contract only."],
            "authority": "Governed read-style capability; the creator (or Greg/governance) sets the initial draft or assigned status. Other transitions are gated in-service by lifecycle authority rules.",
            "intent_tags": ["devjob", "work_assignment", "coordination_contract"],
        },
    ),
    MCPToolDefinition(
        name="ageix.devjob.list",
        capability_id="devjob.list",
        category="devjob",
        description="List DevJob work assignments with optional status, assignee, creator, and repo target filters.",
        input_schema=_object_schema({
            "status": _string("Optional DevJob status filter.", enum=["draft", "assigned", "in_progress", "submitted", "reviewed", "completed", "cancelled"]),
            "assigned_to": _string("Optional assignee identity filter."),
            "created_by": _string("Optional creator identity filter."),
            "repo_target": _string("Optional repository target filter."),
            "limit": _integer("Maximum DevJob summaries to return."),
            "offset": _integer("Zero-based pagination offset."),
        }),
        recommended_next_tools=("ageix.devjob.get",),
    ),
    MCPToolDefinition(
        name="ageix.devjob.get",
        capability_id="devjob.get",
        category="devjob",
        description="Retrieve a DevJob work assignment by ID, including its lifecycle history.",
        input_schema=_object_schema({"job_id": _string("DevJob ID to retrieve.")}, ["job_id"]),
        recommended_next_tools=("ageix.devjob.result.submit",),
    ),
    MCPToolDefinition(
        name="ageix.devjob.result.submit",
        capability_id="devjob.result.submit",
        category="devjob",
        description="Submit a reference-only DevJob result (patch_id, artifact_ids, validation_run_id, branch info) and move the DevJob to submitted, per INTENT-0007.",
        input_schema=_object_schema({
            "job_id": _string("DevJob ID this result is submitted against."),
            "result_summary": _string("Human-readable summary of the work performed."),
            "status": _string("Result status.", enum=["success", "partial", "failed", "blocked"]),
            "public_branch_or_pr": _string("Public branch or pull request reference, by reference only."),
            "branch_name": _string("Branch name the work was committed to, by reference only."),
            "changed_files": _array("List of repository file paths touched, by reference only."),
            "patch_id": _string("Reference to a previously stored governed patch, if any."),
            "artifact_ids": _array("Artifact IDs produced or referenced by this result."),
            "validation_run_id": _string("Reference to a validation run, if any."),
            "validation_notes": _string("Notes about validation status or follow-up."),
            "submitted_by": _string("Explicit submitter identity; defaults to the caller's client_id."),
        }, ["job_id"]),
        recommended_next_tools=("ageix.devjob.get",),
        related_tools=("ageix.patch.metadata", "ageix.validation.run.result", "ageix.artifact.metadata"),
        documentation={
            "use_when": ["Report completion of a DevJob's assigned work by reference, after the actual patch/branch/validation work already exists elsewhere in Ageix."],
            "do_not_use_when": ["Do not use this to generate, apply, or validate a patch — submit only references to artifacts that already exist."],
            "authority": "Restricted to the DevJob's assigned DevWorker; moves the DevJob from in_progress to submitted.",
            "intent_tags": ["devjob", "result_submission", "coordination_contract"],
        },
    ),

    # --- Temporary Chair delegation bridge (Sprint 25.4.5 / 25.4.5.1) --------
    # Surfaces the delegated Chair-directive path on the MCP catalog so a
    # non-Greg delegate (e.g. Lex) can actually reach it. conversation.turn.append
    # remains Greg-only for DIRECTIVE turns; conversation.directive.submit is the
    # governed delegated path. This whole group can be retired with the bridge.
    MCPToolDefinition(
        name="ageix.chair.delegation.create",
        capability_id="chair.delegation.create",
        category="chair_delegation",
        description="Create a temporary, single-use Chair delegation authorizing a delegate to perform one narrowly-scoped Chair-only action. Requires explicit Chair approval (Greg or governance). Temporary bridge, Sprint 25.4.5.",
        input_schema=_object_schema({
            "delegate": _string("Identity being authorized (e.g. 'lex'). Acts as itself; never impersonates the Chair."),
            "allowed_action": _string("The single Chair-only action to authorize (e.g. 'conversation.directive.submit')."),
            "allowed_actions": _array("Alternative to allowed_action: list form (single action preferred for this bridge)."),
            "reason": _string("Why the Chair is granting this delegation."),
            "expires_in_minutes": _integer("Delegation lifetime in minutes (default 30)."),
        }, ["delegate"]),
        recommended_next_tools=("ageix.conversation.directive.submit", "ageix.chair.delegation.get"),
        related_tools=("ageix.chair.delegation.list",),
        documentation={
            "use_when": ["Greg (Chair) needs to explicitly authorize another identity to perform one Chair-only action while no authenticated Human Interface exists."],
            "do_not_use_when": ["Do not use for broad or persistent delegation, multi-action grants, or to bypass Chair authority."],
            "authority": "Restricted to Greg or a governance role. Temporary bridge until the Human Interface is available.",
            "intent_tags": ["chair_delegation", "temporary_bridge", "governance"],
        },
    ),
    MCPToolDefinition(
        name="ageix.chair.delegation.get",
        capability_id="chair.delegation.get",
        category="chair_delegation",
        description="Retrieve a Chair delegation by ID, including status, expiry, and consumption/audit lineage.",
        input_schema=_object_schema({
            "delegation_id": _string("Delegation ID to retrieve."),
        }, ["delegation_id"]),
        related_tools=("ageix.chair.delegation.list",),
    ),
    MCPToolDefinition(
        name="ageix.chair.delegation.list",
        capability_id="chair.delegation.list",
        category="chair_delegation",
        description="List Chair delegations with optional delegate, status, and project filters.",
        input_schema=_object_schema({
            "delegate": _string("Filter by delegate identity."),
            "status": _string("Filter by status.", enum=["active", "consumed", "expired", "revoked"]),
            "limit": _integer("Maximum number of delegations to return."),
            "offset": _integer("Zero-based offset."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.conversation.directive.submit",
        capability_id="conversation.directive.submit",
        category="chair_delegation",
        description="Submit a single Chair-only DIRECTIVE into a conversation under a valid Chair delegation. Verifies and consumes the delegation and records it in the audit trail; the delegate acts as itself (no impersonation). This is the delegated path — conversation.turn.append stays Greg-only for DIRECTIVE turns. Temporary bridge, Sprint 25.4.5.",
        input_schema=_object_schema({
            "conversation_id": _string("Conversation ID to append the directive to."),
            "content": _string("Directive content."),
            "delegation_id": _string("The Chair delegation authorizing this directive."),
            "participant_id": _string("The acting delegate identity (e.g. 'lex'); must match the delegation's delegate."),
            "confidence": {"type": "number", "description": "Confidence from 0.0 to 10.0."},
            "directed_at": _string("Optional agent_role this directive is directed at."),
            "model_id": _string("Underlying model identifier that produced this directive."),
        }, ["conversation_id", "content", "delegation_id"]),
        recommended_next_tools=("ageix.conversation.turn.list",),
        related_tools=("ageix.chair.delegation.create", "ageix.chair.delegation.get"),
        documentation={
            "use_when": ["A non-Greg delegate (e.g. Lex) needs to submit a Chair-only DIRECTIVE authorized by a Chair delegation."],
            "do_not_use_when": ["Do not use without a valid delegation. Greg posts directives directly via conversation.turn.append."],
            "authority": "Requires a valid, unexpired, unconsumed Chair delegation matching the delegate and action. The delegate is recorded as author; Chair authority is preserved.",
            "intent_tags": ["chair_delegation", "conversation_directive", "temporary_bridge"],
        },
    ),
)
