from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class MCPToolDefinition:
    """Declarative public contract for a governed Ageix MCP tool."""

    name: str
    capability_id: str
    category: str
    description: str
    version: str = "1.0"
    requires_project: bool = True
    requires_auth: bool = True
    enabled: bool = True
    experimental: bool = False
    placeholder: bool = False
    placeholder_reason: str | None = None
    input_schema: dict[str, Any] = field(default_factory=dict)
    recommended_next_tools: tuple[str, ...] = ()
    related_tools: tuple[str, ...] = ()
    documentation: dict[str, Any] = field(default_factory=dict)

    def to_discovery_dict(self) -> dict[str, Any]:
        workflow = {
            "recommended_next_tools": list(self.recommended_next_tools),
            "related_tools": list(self.related_tools),
        }
        return {
            "tool_name": self.name,
            "name": self.name,
            "capability_id": self.capability_id,
            "category": self.category,
            "description": self.description,
            "version": self.version,
            "requires_project": self.requires_project,
            "requires_auth": self.requires_auth,
            "enabled": self.enabled,
            "experimental": self.experimental,
            "placeholder": self.placeholder,
            "placeholder_reason": self.placeholder_reason,
            "input_schema": self.input_schema or {"type": "object", "properties": {}, "required": []},
            "workflow": workflow,
            "recommended_next_tools": list(self.recommended_next_tools),
            "related_tools": list(self.related_tools),
            "documentation": self.documentation,
        }


def _object_schema(properties: dict[str, dict[str, Any]], required: list[str] | None = None) -> dict[str, Any]:
    return {"type": "object", "properties": properties, "required": required or []}


def _string(description: str = "", *, enum: list[str] | None = None) -> dict[str, Any]:
    payload: dict[str, Any] = {"type": "string"}
    if description:
        payload["description"] = description
    if enum:
        payload["enum"] = enum
    return payload


def _integer(description: str = "") -> dict[str, Any]:
    payload: dict[str, Any] = {"type": "integer"}
    if description:
        payload["description"] = description
    return payload


def _array(description: str = "") -> dict[str, Any]:
    payload: dict[str, Any] = {"type": "array"}
    if description:
        payload["description"] = description
    return payload


def _object(description: str = "") -> dict[str, Any]:
    payload: dict[str, Any] = {"type": "object"}
    if description:
        payload["description"] = description
    return payload

MCP_TOOL_DEFINITIONS: tuple[MCPToolDefinition, ...] = (
    MCPToolDefinition(
        name="ageix.health",
        capability_id="ageix.health",
        category="system",
        description="Return Ageix MCP/capability interface health.",
        requires_project=False,
    ),
    MCPToolDefinition(
        name="ageix.capabilities.list",
        capability_id="capabilities.list",
        category="capability",
        description="List governed Ageix capabilities and MCP tools exposed to external clients with optional filtering and pagination.",
        requires_project=False,
        input_schema=_object_schema({
            "category": _string("Optional capability/tool category filter."),
            "query": _string("Optional case-insensitive capability/tool search text."),
            "limit": _integer("Maximum rows to return."),
            "offset": _integer("Zero-based pagination offset."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.capabilities.execute",
        capability_id="capabilities.execute",
        category="capability",
        description="Execute a governed Ageix capability by capability ID.",
        input_schema=_object_schema({
            "capability_id": _string("Capability ID to execute through governed authorization."),
            "arguments": _object("Capability arguments."),
        }, ["capability_id"]),
    ),
    MCPToolDefinition(
        name="ageix.projects.current",
        capability_id="project.current",
        category="project",
        description="Return the explicitly selected current project profile.",
    ),
    MCPToolDefinition(
        name="ageix.projects.profile",
        capability_id="project.profile",
        category="project",
        description="Return a project profile by project ID.",
        input_schema=_object_schema({"project_id": _string("Explicit project ID.")}, ["project_id"]),
    ),
    MCPToolDefinition(
        name="ageix.projects.list",
        capability_id="project.list",
        category="project",
        description="List registered Ageix projects visible to the governed interface.",
        requires_project=False,
    ),
    MCPToolDefinition(
        name="ageix.proposals.submit",
        capability_id="proposal.submit",
        category="proposal",
        description="Submit a governed proposal for Chair evaluation.",
        input_schema=_object_schema({
            "objective": _string("Proposal objective for Chair evaluation."),
            "proposal_type": _string("Proposal type.", enum=["investigation", "architecture", "implementation", "research"]),
            "parent_proposal_id": _string("Optional parent proposal ID."),
            "proposal_version": _integer("Optional proposal version."),
            "linked_evidence": _array("Linked evidence IDs."),
            "linked_consultations": _array("Linked consultation IDs."),
            "required_consultations": _array("Required consultation types."),
            "conditions": _array("Proposal conditions."),
            "metadata": _object("Additional proposal metadata."),
        }, ["objective"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.consultations.submit"),
        related_tools=("ageix.proposals.get", "ageix.proposals.list"),
    ),
    MCPToolDefinition(
        name="ageix.proposals.get",
        capability_id="proposal.details",
        category="proposal",
        description="Retrieve a governed proposal by ID.",
        input_schema=_object_schema({"proposal_id": _string("Proposal ID to retrieve.")}, ["proposal_id"]),
    ),
    MCPToolDefinition(
        name="ageix.proposals.list",
        capability_id="proposal.list",
        category="proposal",
        description="List governed proposals for a project/session.",
        input_schema=_object_schema({"limit": _integer("Maximum number of proposals to return.")}),
    ),
    MCPToolDefinition(
        name="ageix.proposals.status",
        capability_id="proposal.status",
        category="proposal",
        description="Return the current status for a governed proposal.",
        input_schema=_object_schema({"proposal_id": _string("Proposal ID to check.")}, ["proposal_id"]),
        recommended_next_tools=("ageix.consultations.submit",),
    ),
    MCPToolDefinition(
        name="ageix.consultations.submit",
        capability_id="consultation.submit",
        category="consultation",
        description="Submit external consultation input for a governed proposal.",
        input_schema=_object_schema({
            "proposal_id": _string("Proposal ID receiving consultation evidence."),
            "consultation_type": _string("Consultation type."),
            "summary": _string("Summary or recommendation text."),
            "confidence": {"type": "number", "description": "Confidence from 0.0 to 1.0."},
            "disposition": _string("Consultation disposition."),
            "evidence_sufficient": {"type": "boolean"},
            "findings": _array("Findings."),
            "concerns": _array("Concerns or risks."),
            "recommendations": _array("Suggested improvements."),
            "metadata": _object("Additional consultation metadata."),
        }, ["proposal_id", "consultation_type"]),
        recommended_next_tools=("ageix.consultations.get", "ageix.proposals.status"),
        related_tools=("ageix.consultations.list",),
    ),
    MCPToolDefinition(
        name="ageix.consultations.get",
        capability_id="consultation.details",
        category="consultation",
        description="Retrieve a submitted consultation by ID.",
        input_schema=_object_schema({"consultation_id": _string("Consultation ID to retrieve.")}, ["consultation_id"]),
    ),
    MCPToolDefinition(
        name="ageix.consultations.list",
        capability_id="consultation.list",
        category="consultation",
        description="List governed consultations.",
        input_schema=_object_schema({"limit": _integer("Maximum number of consultations to return.")}),
    ),

    MCPToolDefinition(
        name="ageix.architecture.list",
        capability_id="architecture.list",
        category="architecture",
        description="List governed architecture hierarchy nodes visible to the current project.",
        input_schema=_object_schema({
            "node_type": _string("Optional architecture node type filter.", enum=["project", "domain", "component", "service"]),
            "parent_id": _string("Optional parent architecture ID filter."),
        }),
        recommended_next_tools=("ageix.architecture.details", "ageix.architecture.children"),
        related_tools=("ageix.architecture.subtree",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.details",
        capability_id="architecture.details",
        category="architecture",
        description="Retrieve one governed architecture node by architecture ID or stable path.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path, such as Ageix.MCPPlatform.ToolRegistry."),
        }),
        recommended_next_tools=("ageix.architecture.children", "ageix.architecture.subtree"),
        related_tools=("ageix.architecture.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.children",
        capability_id="architecture.children",
        category="architecture",
        description="Retrieve direct children for a governed architecture node.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "include_node": {"type": "boolean", "description": "Include the parent node payload."},
        }),
        recommended_next_tools=("ageix.architecture.details", "ageix.architecture.subtree"),
        related_tools=("ageix.architecture.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.subtree",
        capability_id="architecture.subtree",
        category="architecture",
        description="Retrieve a governed architecture hierarchy subtree from a node.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
        }),
        recommended_next_tools=("ageix.architecture.details",),
        related_tools=("ageix.architecture.children", "ageix.architecture.list"),
    ),

    MCPToolDefinition(
        name="ageix.architecture.context",
        capability_id="architecture.context",
        category="architecture",
        description="Build summary-first architecture context for a governed architecture node without repository-wide discovery.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "include_detail": {"type": "boolean", "description": "Include detailed node and approved description payloads."},
        }),
        recommended_next_tools=("ageix.architecture.details", "ageix.evidence.package.details"),
        related_tools=("ageix.architecture.children", "ageix.architecture.subtree", "ageix.decision.trace.details"),
    ),

    MCPToolDefinition(
        name="ageix.architecture.health",
        capability_id="architecture.health",
        category="architecture",
        description="Return deterministic architecture health indicators for one governed architecture node.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
        }),
        recommended_next_tools=("ageix.architecture.coverage", "ageix.architecture.context"),
        related_tools=("ageix.architecture.details", "ageix.evidence.package.summary"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.coverage",
        capability_id="architecture.coverage",
        category="architecture",
        description="Return deterministic architecture coverage metrics for a project registry baseline.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
        }, ["project_id"]),
        recommended_next_tools=("ageix.architecture.health", "ageix.architecture.list"),
        related_tools=("ageix.architecture.subtree",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.baseline.validate",
        capability_id="architecture.baseline.validate",
        category="architecture",
        description="Validate an architecture baseline using deterministic registry and health data.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
        }, ["project_id"]),
        recommended_next_tools=("ageix.architecture.coverage", "ageix.architecture.review.submit"),
        related_tools=("ageix.architecture.health",),
    ),


    MCPToolDefinition(
        name="ageix.architecture.review.submit",
        capability_id="architecture.review.submit",
        category="architecture",
        description="Submit a governed architecture review from an authorized architect MCP partner.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "summary": _string("Review summary."),
            "rationale": _string("Review rationale."),
            "no_findings": {"type": "boolean", "description": "True when the review found no concerns."},
            "metadata": _object("Additional review metadata."),
        }),
        recommended_next_tools=("ageix.architecture.finding.submit", "ageix.architecture.review.get"),
        related_tools=("ageix.architecture.review.list", "ageix.architecture.health"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.review.get",
        capability_id="architecture.review.get",
        category="architecture",
        description="Retrieve a governed architecture review by review ID.",
        input_schema=_object_schema({"review_id": _string("Architecture review ID.")}, ["review_id"]),
        related_tools=("ageix.architecture.review.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.review.list",
        capability_id="architecture.review.list",
        category="architecture",
        description="List governed architecture reviews for a project or architecture node.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "limit": _integer("Maximum reviews to return."),
        }),
        related_tools=("ageix.architecture.review.get",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.finding.submit",
        capability_id="architecture.finding.submit",
        category="architecture",
        description="Submit a structured architecture finding from an authorized architect MCP partner.",
        input_schema=_object_schema({
            "review_id": _string("Optional architecture review ID."),
            "architecture_id": _string("Single affected architecture node ID."),
            "path": _string("Single affected stable architecture path."),
            "affected_architecture_ids": _array("Affected architecture IDs or paths."),
            "severity": _string("Finding severity.", enum=["informational", "concern", "significant_concern", "critical_concern"]),
            "category": _string("Finding category.", enum=["documentation_gap", "evidence_gap", "decision_gap", "architecture_inconsistency", "architecture_staleness", "coverage_gap", "intent_miss", "requires_additional_discovery", "other"]),
            "summary": _string("Finding summary."),
            "rationale": _string("Finding rationale."),
            "other_explanation": _string("Required when category is other."),
            "metadata": _object("Additional finding metadata."),
        }, ["summary"]),
        recommended_next_tools=("ageix.architecture.challenge.submit", "ageix.architecture.review.get"),
        related_tools=("ageix.architecture.health",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.challenge.submit",
        capability_id="architecture.challenge.submit",
        category="architecture",
        description="Submit an architecture challenge with context and intent.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "finding_id": _string("Optional finding ID that prompted the challenge."),
            "challenge_summary": _string("Challenge summary."),
            "context": _string("Architectural context for the disagreement."),
            "intent": _string("Architectural intent behind the challenge."),
            "rationale": _string("Challenge rationale."),
            "proposed_direction": _string("Optional proposed direction."),
            "metadata": _object("Additional challenge metadata."),
        }, ["challenge_summary", "context", "intent"]),
        recommended_next_tools=("ageix.architecture.revision.propose", "ageix.architecture.challenge.get"),
        related_tools=("ageix.architecture.challenge.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.challenge.get",
        capability_id="architecture.challenge.get",
        category="architecture",
        description="Retrieve a governed architecture challenge by challenge ID.",
        input_schema=_object_schema({"challenge_id": _string("Architecture challenge ID.")}, ["challenge_id"]),
        related_tools=("ageix.architecture.challenge.list",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.challenge.list",
        capability_id="architecture.challenge.list",
        category="architecture",
        description="List governed architecture challenges for a project or architecture node.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "limit": _integer("Maximum challenges to return."),
        }),
        related_tools=("ageix.architecture.challenge.get",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.revision.propose",
        capability_id="architecture.revision.propose",
        category="architecture",
        description="Propose a governed architecture registry revision through the existing proposal system; does not mutate the registry directly.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "challenge_id": _string("Optional challenge ID."),
            "objective": _string("Revision objective for Chair governance."),
            "proposed_changes": _object("Allowed architecture-registry-only change set."),
            "metadata": _object("Additional revision proposal metadata."),
        }, ["objective", "proposed_changes"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.proposals.get"),
        related_tools=("ageix.architecture.challenge.get", "ageix.proposals.list", "ageix.architecture.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.revisions",
        capability_id="architecture.revisions",
        category="architecture",
        description="List immutable governed architecture revisions for a project or architecture node.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "limit": _integer("Maximum revisions to return."),
        }),
        recommended_next_tools=("ageix.architecture.revision.details", "ageix.architecture.baseline.current"),
        related_tools=("ageix.architecture.history",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.revision.details",
        capability_id="architecture.revision.details",
        category="architecture",
        description="Retrieve immutable architecture revision details and optional full architecture snapshot.",
        input_schema=_object_schema({
            "revision_id": _string("Architecture revision ID."),
            "include_snapshot": {"type": "boolean", "description": "Include the immutable full architecture snapshot."},
        }, ["revision_id"]),
        related_tools=("ageix.architecture.revisions", "ageix.architecture.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.history",
        capability_id="architecture.history",
        category="architecture",
        description="Retrieve immutable architecture revision history and the current authoritative baseline.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "project_id": _string("Explicit project ID."),
        }),
        recommended_next_tools=("ageix.architecture.baseline.current", "ageix.architecture.revision.details"),
        related_tools=("ageix.architecture.revisions",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.baseline.current",
        capability_id="architecture.baseline.current",
        category="architecture",
        description="Retrieve the current authoritative architecture baseline for an architecture node.",
        input_schema=_object_schema({
            "architecture_id": _string("Architecture node ID."),
            "path": _string("Stable architecture path."),
            "project_id": _string("Explicit project ID."),
            "include_snapshot": {"type": "boolean", "description": "Include the immutable full architecture snapshot."},
        }),
        related_tools=("ageix.architecture.history", "ageix.architecture.revision.details"),
    ),


    MCPToolDefinition(
        name="ageix.architecture.adr.propose",
        capability_id="architecture.adr.propose",
        category="architecture",
        description="Propose a governed Architecture Decision Record through the existing proposal system; does not directly accept or mutate ADR history.",
        input_schema=_object_schema({
            "title": _string("ADR title."),
            "context": _string("Decision context and architectural discussion background."),
            "decision": _string("Decision being proposed."),
            "rationale": _string("Rationale for the proposed decision."),
            "alternatives_considered": {"type": "array", "items": {"type": "string"}, "description": "Alternatives considered."},
            "consequences": {"type": "array", "items": {"type": "string"}, "description": "Consequences of accepting the decision."},
            "tradeoffs": {"type": "array", "items": {"type": "string"}, "description": "Tradeoffs accepted by the decision."},
            "future_considerations": {"type": "array", "items": {"type": "string"}, "description": "Future implications or backlog hints."},
            "architecture_ids": {"type": "array", "items": {"type": "string"}, "description": "Linked architecture IDs."},
            "revision_ids": {"type": "array", "items": {"type": "string"}, "description": "Linked architecture revision IDs."},
            "supersedes_adr_id": _string("Optional ADR ID superseded by this proposal."),
            "related_adr_ids": {"type": "array", "items": {"type": "string"}, "description": "Related ADR IDs."},
            "evidence_package_ids": {"type": "array", "items": {"type": "string"}, "description": "Linked evidence package IDs."},
            "metadata": _object("Additional ADR proposal metadata."),
        }, ["title", "context", "decision", "rationale"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.proposals.get"),
        related_tools=("ageix.architecture.adrs", "ageix.architecture.adr.details", "ageix.architecture.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.adrs",
        capability_id="architecture.adrs",
        category="architecture",
        description="List governed Architecture Decision Records by project, architecture, revision, or status.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "status": _string("Optional ADR status filter."),
            "limit": _integer("Maximum ADRs to return."),
        }),
        recommended_next_tools=("ageix.architecture.adr.details", "ageix.architecture.adr.history"),
        related_tools=("ageix.architecture.history",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.adr.details",
        capability_id="architecture.adr.details",
        category="architecture",
        description="Retrieve one governed Architecture Decision Record.",
        input_schema=_object_schema({"adr_id": _string("Architecture Decision Record ID.")}, ["adr_id"]),
        related_tools=("ageix.architecture.adrs", "ageix.architecture.adr.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.adr.history",
        capability_id="architecture.adr.history",
        category="architecture",
        description="Retrieve immutable Architecture Decision Record supersession history.",
        input_schema=_object_schema({"adr_id": _string("Architecture Decision Record ID.")}, ["adr_id"]),
        related_tools=("ageix.architecture.adrs", "ageix.architecture.adr.details"),
    ),

    MCPToolDefinition(
        name="ageix.workflow.current",
        capability_id="workflow.current",
        category="workflow",
        description="Return advisory workflow/session state for the current governed MCP session.",
        input_schema=_object_schema({}),
        recommended_next_tools=("ageix.proposals.submit", "ageix.consultations.submit", "ageix.proposals.status"),
    ),
    MCPToolDefinition(
        name="ageix.identity.current",
        capability_id="identity.current",
        category="identity",
        description="Return resolved MCP caller identity and governance profile for the current request context.",
        requires_project=True,
        input_schema=_object_schema({}),
        related_tools=("ageix.workflow.current",),
    ),
    MCPToolDefinition(
        name="ageix.audit.recent",
        capability_id="audit.recent",
        category="audit",
        description="Return recent scoped audit records.",
        input_schema=_object_schema({"limit": _integer("Maximum number of audit records to return.")}),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.list",
        capability_id="evidence.package.list",
        category="evidence",
        description="List project-scoped immutable evidence package summaries with pagination and filters.",
        input_schema=_object_schema({
            "limit": _integer("Maximum package summaries to return."),
            "offset": _integer("Zero-based pagination offset."),
            "proposal_id": _string("Optional proposal ID filter."),
            "evidence_plan_id": _string("Optional evidence plan ID filter."),
            "stale": {"type": "boolean", "description": "Optional stale/fresh filter."},
            "objective_contains": _string("Case-insensitive objective contains filter."),
            "context_contains": _string("Case-insensitive package context contains filter."),
            "created_before": _string("Optional ISO timestamp upper bound."),
            "created_after": _string("Optional ISO timestamp lower bound."),
        }),
        recommended_next_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness", "ageix.evidence.package.retrieve"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.search",
        capability_id="evidence.package.search",
        category="evidence",
        description="Search project-scoped immutable evidence package summaries without returning package contents.",
        input_schema=_object_schema({
            "query": _string("Search text matched against package objective/context."),
            "limit": _integer("Maximum package summaries to return."),
            "offset": _integer("Zero-based pagination offset."),
            "proposal_id": _string("Optional proposal ID filter."),
            "evidence_plan_id": _string("Optional evidence plan ID filter."),
            "stale": {"type": "boolean", "description": "Optional stale/fresh filter."},
            "objective_contains": _string("Case-insensitive objective contains filter."),
            "context_contains": _string("Case-insensitive package context contains filter."),
        }),
        recommended_next_tools=("ageix.evidence.package.details", "ageix.evidence.package.retrieve", "ageix.evidence.package.recommend"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.details",
        capability_id="evidence.package.details",
        category="evidence",
        description="Inspect package metadata, freshness, counts, and provenance manifest without returning package contents.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.retrieve", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.freshness",
        capability_id="evidence.package.freshness",
        category="evidence",
        description="Evaluate current repository content freshness for one evidence package and update the index.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.details",),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.rehydrate",
        capability_id="evidence.package.rehydrate",
        category="evidence",
        description="Legacy alias: return one immutable historical evidence package by package ID without freshness evaluation.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.retrieve",
        capability_id="evidence.package.retrieve",
        category="evidence",
        description="Retrieve immutable historical evidence package contents after an explicit package request.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.recommend",
        capability_id="evidence.package.recommend",
        category="evidence",
        description="Recommend visible historical evidence packages for a new objective; advisory to Chair only.",
        input_schema=_object_schema({
            "objective": _string("Objective to compare against visible package history."),
            "limit": _integer("Maximum recommendations to return."),
            "min_similarity": {"type": "number", "description": "Minimum deterministic similarity threshold."},
        }, ["objective"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.reuse"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.reuse",
        capability_id="evidence.package.reuse",
        category="evidence",
        description="Create a new immutable child package that records Chair-approved reuse of a visible parent package.",
        input_schema=_object_schema({
            "package_id": _string("Parent evidence package ID."),
            "objective": _string("Optional child package objective."),
            "lineage_type": _string("Lineage type.", enum=["reuse", "refresh", "expansion", "derived"]),
            "reuse_reason": _string("Chair reuse decision rationale."),
        }, ["package_id"]),
        related_tools=("ageix.evidence.package.lineage", "ageix.evidence.package.details"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.deprecate",
        capability_id="evidence.package.deprecate",
        category="evidence",
        description="Mark a visible package deprecated in catalog metadata without mutating package contents.",
        input_schema=_object_schema({
            "package_id": _string("Evidence package ID."),
            "reason": _string("Governance deprecation rationale."),
        }, ["package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.recommend"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.supersede",
        capability_id="evidence.package.supersede",
        category="evidence",
        description="Mark a visible package superseded by a newer compatible package without mutating package contents.",
        input_schema=_object_schema({
            "package_id": _string("Evidence package ID being superseded."),
            "superseded_by_package_id": _string("Newer replacement evidence package ID."),
            "reason": _string("Governance supersession rationale."),
        }, ["package_id", "superseded_by_package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.recommend"),
    ),
    MCPToolDefinition(
        name="ageix.evidence.package.lineage",
        capability_id="evidence.package.lineage",
        category="evidence",
        description="Return visible parent, child, ancestor, and descendant package lineage.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.retrieve"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.create",
        capability_id="decision.trace.create",
        category="decision_trace",
        description="Internal Chair-only decision trace creation capability; not exposed as an enabled MCP tool.",
        enabled=False,
        input_schema=_object_schema({
            "decision_summary": _string("Decision summary."),
            "outcome": _string("Decision outcome.", enum=["approved", "rejected", "implemented", "superseded", "abandoned", "deferred", "backlog"]),
            "decision_id": _string("Optional external decision ID."),
            "decision_type": _string("Decision type."),
            "proposal_id": _string("Linked proposal ID."),
            "evidence_package_ids": _array("Linked evidence package IDs."),
            "consultation_ids": _array("Linked consultation IDs."),
            "validation_ids": _array("Linked validation IDs."),
            "repository_snapshot": _object("Repository snapshot metadata."),
            "reason": _string("Decision rationale."),
            "outcome_metadata": _object("Future outcome hook metadata such as backlog/deferred details."),
            "related_entities": _object("Extensible related entity IDs for future architecture links."),
            "metadata": _object("Additional trace metadata."),
        }, ["decision_summary", "outcome"]),
        related_tools=("ageix.decision.trace.get", "ageix.decision.trace.list"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.get",
        capability_id="decision.trace.get",
        category="decision_trace",
        description="Legacy alias: retrieve one append-only decision trace with linked package summaries and current freshness awareness.",
        input_schema=_object_schema({
            "trace_id": _string("Decision trace ID."),
            "include_freshness": {"type": "boolean", "description": "Include current package freshness indicators."},
        }, ["trace_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.details",
        capability_id="decision.trace.details",
        category="decision_trace",
        description="Retrieve one append-only decision trace with linked package summaries and current freshness awareness.",
        input_schema=_object_schema({
            "trace_id": _string("Decision trace ID."),
            "include_freshness": {"type": "boolean", "description": "Include current package freshness indicators."},
        }, ["trace_id"]),
        related_tools=("ageix.evidence.package.details", "ageix.evidence.package.freshness"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.list",
        capability_id="decision.trace.list",
        category="decision_trace",
        description="List project-scoped decision traces by proposal, package, outcome, or summary text.",
        input_schema=_object_schema({
            "limit": _integer("Maximum traces to return."),
            "offset": _integer("Zero-based pagination offset."),
            "decision_id": _string("Decision ID filter."),
            "proposal_id": _string("Proposal ID filter."),
            "evidence_package_id": _string("Evidence package ID filter."),
            "outcome": _string("Outcome filter.", enum=["approved", "rejected", "implemented", "superseded", "abandoned", "deferred", "backlog"]),
            "summary_contains": _string("Case-insensitive decision summary contains filter."),
        }),
        related_tools=("ageix.decision.trace.get",),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.search",
        capability_id="decision.trace.search",
        category="decision_trace",
        description="Search project-scoped decision traces by query, proposal, package, outcome, or summary text.",
        input_schema=_object_schema({
            "query": _string("Search text matched against decision summary."),
            "limit": _integer("Maximum traces to return."),
            "offset": _integer("Zero-based pagination offset."),
            "decision_id": _string("Decision ID filter."),
            "proposal_id": _string("Proposal ID filter."),
            "evidence_package_id": _string("Evidence package ID filter."),
            "outcome": _string("Outcome filter.", enum=["approved", "rejected", "implemented", "superseded", "abandoned", "deferred", "backlog"]),
            "summary_contains": _string("Case-insensitive decision summary contains filter."),
        }),
        related_tools=("ageix.decision.trace.details",),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.history",
        capability_id="decision.trace.history",
        category="decision_trace",
        description="Find historical decision traces related to a package, proposal, or decision ID.",
        input_schema=_object_schema({
            "package_id": _string("Evidence package ID filter."),
            "proposal_id": _string("Proposal ID filter."),
            "decision_id": _string("Decision ID filter."),
            "limit": _integer("Maximum traces to return."),
            "offset": _integer("Zero-based pagination offset."),
        }),
        related_tools=("ageix.decision.trace.details", "ageix.evidence.package.details"),
    ),
    MCPToolDefinition(
        name="ageix.decision.trace.package_history",
        capability_id="decision.trace.package_history",
        category="decision_trace",
        description="Legacy alias: find decision traces that used a specific evidence package.",
        input_schema=_object_schema({"package_id": _string("Evidence package ID.")}, ["package_id"]),
        related_tools=("ageix.decision.trace.get", "ageix.evidence.package.details"),
    ),

    MCPToolDefinition(
        name="ageix.architecture.principle.propose",
        capability_id="architecture.principle.propose",
        category="architecture",
        description="Propose a governed Architecture Principle through the existing proposal system; does not directly accept or mutate guidance history.",
        input_schema=_object_schema({
            "title": _string("Principle title."),
            "statement": _string("Constraint, rule, or standard statement."),
            "rationale": _string("Principle rationale."),
            "scope": _string("Principle scope."),
            "architecture_ids": _array("Linked architecture IDs."),
            "adr_ids": _array("Linked ADR IDs."),
            "revision_ids": _array("Linked architecture revision IDs."),
            "supersedes_principle_id": _string("Optional principle ID superseded by this proposal."),
            "related_principle_ids": _array("Related principle IDs."),
            "evidence_package_ids": _array("Linked evidence package IDs."),
            "metadata": _object("Additional principle proposal metadata."),
        }, ["title", "statement"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.proposals.get"),
        related_tools=("ageix.architecture.principles", "ageix.architecture.principle.details", "ageix.architecture.guidance"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.principles",
        capability_id="architecture.principles",
        category="architecture",
        description="List governed Architecture Principles by project, architecture, ADR, revision, or status.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "adr_id": _string("Optional ADR ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "status": _string("Optional principle status filter."),
            "limit": _integer("Maximum principles to return."),
        }),
        recommended_next_tools=("ageix.architecture.principle.details", "ageix.architecture.principle.history"),
        related_tools=("ageix.architecture.guidance",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.principle.details",
        capability_id="architecture.principle.details",
        category="architecture",
        description="Retrieve one governed Architecture Principle.",
        input_schema=_object_schema({"principle_id": _string("Architecture Principle ID.")}, ["principle_id"]),
        related_tools=("ageix.architecture.principles", "ageix.architecture.principle.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.principle.history",
        capability_id="architecture.principle.history",
        category="architecture",
        description="Retrieve immutable Architecture Principle supersession history.",
        input_schema=_object_schema({"principle_id": _string("Architecture Principle ID.")}, ["principle_id"]),
        related_tools=("ageix.architecture.principles", "ageix.architecture.principle.details"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.intent.propose",
        capability_id="architecture.intent.propose",
        category="architecture",
        description="Propose governed Architecture Intent through the existing proposal system; does not directly accept or mutate guidance history.",
        input_schema=_object_schema({
            "title": _string("Intent title."),
            "summary": _string("Intent summary or directional architectural aim."),
            "details": _string("Intent details."),
            "scope": _string("Intent scope."),
            "future_considerations": _array("Future implications or backlog hints."),
            "architecture_ids": _array("Linked architecture IDs."),
            "adr_ids": _array("Linked ADR IDs."),
            "principle_ids": _array("Linked principle IDs."),
            "revision_ids": _array("Linked architecture revision IDs."),
            "supersedes_intent_id": _string("Optional intent ID superseded by this proposal."),
            "related_intent_ids": _array("Related intent IDs."),
            "evidence_package_ids": _array("Linked evidence package IDs."),
            "metadata": _object("Additional intent proposal metadata."),
        }, ["title", "summary"]),
        recommended_next_tools=("ageix.proposals.status", "ageix.proposals.get"),
        related_tools=("ageix.architecture.intents", "ageix.architecture.intent.details", "ageix.architecture.guidance"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.intents",
        capability_id="architecture.intents",
        category="architecture",
        description="List governed Architecture Intent records by project, architecture, ADR, principle, revision, or status.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "adr_id": _string("Optional ADR ID."),
            "principle_id": _string("Optional principle ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "status": _string("Optional intent status filter."),
            "limit": _integer("Maximum intents to return."),
        }),
        recommended_next_tools=("ageix.architecture.intent.details", "ageix.architecture.intent.history"),
        related_tools=("ageix.architecture.guidance",),
    ),
    MCPToolDefinition(
        name="ageix.architecture.intent.details",
        capability_id="architecture.intent.details",
        category="architecture",
        description="Retrieve one governed Architecture Intent record.",
        input_schema=_object_schema({"intent_id": _string("Architecture Intent ID.")}, ["intent_id"]),
        related_tools=("ageix.architecture.intents", "ageix.architecture.intent.history"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.intent.history",
        capability_id="architecture.intent.history",
        category="architecture",
        description="Retrieve immutable Architecture Intent supersession history.",
        input_schema=_object_schema({"intent_id": _string("Architecture Intent ID.")}, ["intent_id"]),
        related_tools=("ageix.architecture.intents", "ageix.architecture.intent.details"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.guidance",
        capability_id="architecture.guidance",
        category="architecture",
        description="Return derived architecture guidance from accepted principles and intent for an architecture node, ADR, revision, or project.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "adr_id": _string("Optional ADR ID."),
            "revision_id": _string("Optional architecture revision ID."),
        }),
        related_tools=("ageix.architecture.principles", "ageix.architecture.intents", "ageix.architecture.context"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.guidance.context",
        capability_id="architecture.guidance.context",
        category="architecture",
        description="Build or explicitly persist a summary-first Architecture Guidance Context Package.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "architecture_id": _string("Optional architecture node ID."),
            "path": _string("Optional stable architecture path."),
            "adr_id": _string("Optional ADR ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "principle_id": _string("Optional Architecture Principle ID."),
            "intent_id": _string("Optional Architecture Intent ID."),
            "persist": {"type": "boolean", "description": "Persist immutable GUIDECTX package snapshot when true."},
        }),
        related_tools=("ageix.architecture.guidance", "ageix.architecture.context", "ageix.architecture.principles", "ageix.architecture.intents"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.guidance.context.get",
        capability_id="architecture.guidance.context.get",
        category="architecture",
        description="Retrieve a persisted Architecture Guidance Context Package by ID.",
        input_schema=_object_schema({"package_id": _string("GUIDECTX package ID.")}, ["package_id"]),
        related_tools=("ageix.architecture.guidance.context",),
    ),

    MCPToolDefinition(
        name="ageix.architecture.work.context",
        capability_id="architecture.work.context",
        category="architecture",
        description="Build or explicitly persist a summary-first Architecture Work Context Package.",
        input_schema=_object_schema({
            "project_id": _string("Explicit project ID."),
            "work_summary": _string("Human-readable summary of the proposed work."),
            "architecture_id": _string("Optional architecture node ID."),
            "architecture_ids": {"type": "array", "description": "Optional architecture node IDs."},
            "path": _string("Optional stable architecture path."),
            "adr_id": _string("Optional ADR ID."),
            "revision_id": _string("Optional architecture revision ID."),
            "principle_id": _string("Optional Architecture Principle ID."),
            "intent_id": _string("Optional Architecture Intent ID."),
            "node_key": _string("Optional exact architecture node key."),
            "name": _string("Optional exact architecture node name."),
            "max_depth": _integer("Impact traversal depth. Sprint 18.9 supports 1 only."),
            "persist": {"type": "boolean", "description": "Persist immutable WORKCTX package snapshot when true."},
            "persist_guidance_context": {"type": "boolean", "description": "Persist underlying GUIDECTX snapshot when true."},
        }),
        related_tools=("ageix.architecture.guidance.context", "ageix.architecture.context", "ageix.architecture.details"),
    ),
    MCPToolDefinition(
        name="ageix.architecture.work.context.get",
        capability_id="architecture.work.context.get",
        category="architecture",
        description="Retrieve a persisted Architecture Work Context Package by ID.",
        input_schema=_object_schema({"work_context_id": _string("WORKCTX package ID.")}, ["work_context_id"]),
        related_tools=("ageix.architecture.work.context",),
    ),

    MCPToolDefinition(
        name="ageix.validation.scenarios.list",
        capability_id="validation.scenarios.list",
        category="validation",
        description="Reserved validation sandbox scenario discovery contract.",
        experimental=True,
        placeholder=True,
        placeholder_reason="validation sandbox not yet implemented",
    ),
    MCPToolDefinition(
        name="ageix.validation.scenario.request",
        capability_id="validation.scenario.request",
        category="validation",
        description="Reserved governed validation sandbox scenario request contract.",
        experimental=True,
        placeholder=True,
        placeholder_reason="validation sandbox not yet implemented",
        input_schema=_object_schema({"scenario": _string("Validation scenario identifier.")}),
        recommended_next_tools=("ageix.validation.result.get",),
    ),
    MCPToolDefinition(
        name="ageix.validation.result.get",
        capability_id="validation.result.get",
        category="validation",
        description="Reserved governed validation sandbox result retrieval contract.",
        experimental=True,
        placeholder=True,
        placeholder_reason="validation sandbox not yet implemented",
        input_schema=_object_schema({"result_id": _string("Validation result identifier.")}, ["result_id"]),
    ),
    MCPToolDefinition(
        name="ageix.artifact.list",
        capability_id="artifact.list",
        category="artifact",
        description="List governed artifacts with pagination and filters.",
        input_schema=_object_schema({
            "artifact_category": _string("Optional artifact category filter."),
            "artifact_type": _string("Optional artifact type filter."),
            "source_id": _string("Optional source ID filter, such as validation run or archive ID."),
            "created_by": _string("Optional producer capability filter."),
            "limit": _integer("Maximum artifacts to return."),
            "offset": _integer("Zero-based artifact offset."),
        }),
        recommended_next_tools=("ageix.artifact.metadata", "ageix.artifact.get"),
    ),
    MCPToolDefinition(
        name="ageix.artifact.get",
        capability_id="artifact.get",
        category="artifact",
        description="Retrieve one governed artifact registry record.",
        input_schema=_object_schema({"artifact_id": _string("Artifact ID.")}, ["artifact_id"]),
    ),
    MCPToolDefinition(
        name="ageix.artifact.metadata",
        capability_id="artifact.metadata",
        category="artifact",
        description="Retrieve summary-first artifact metadata and relationships.",
        input_schema=_object_schema({"artifact_id": _string("Artifact ID.")}, ["artifact_id"]),
        related_tools=("ageix.artifact.get",),
    ),

    MCPToolDefinition(
        name="ageix.artifact.push",
        capability_id="artifact.push",
        category="artifact_delivery",
        description="Deliver an existing governed artifact to an approved destination.",
        input_schema=_object_schema({
            "artifact_id": _string("Artifact ID to deliver."),
            "destination": _string("Approved delivery destination.", enum=["local_export"]),
        }, ["artifact_id"]),
        recommended_next_tools=("ageix.artifact.delivery.get", "ageix.artifact.delivery.list"),
    ),
    MCPToolDefinition(
        name="ageix.artifact.delivery.get",
        capability_id="artifact.delivery.get",
        category="artifact_delivery",
        description="Retrieve one artifact delivery record.",
        input_schema=_object_schema({"delivery_id": _string("Artifact delivery ID.")}, ["delivery_id"]),
    ),
    MCPToolDefinition(
        name="ageix.artifact.delivery.list",
        capability_id="artifact.delivery.list",
        category="artifact_delivery",
        description="List artifact delivery records with pagination and filters.",
        input_schema=_object_schema({
            "artifact_id": _string("Optional artifact ID filter."),
            "destination": _string("Optional destination filter."),
            "status": _string("Optional delivery status filter."),
            "limit": _integer("Maximum deliveries to return."),
            "offset": _integer("Zero-based delivery offset."),
        }),
    ),

    MCPToolDefinition(
        name="ageix.repo.info",
        capability_id="repo.info",
        category="repository",
        description="Return summary-first repository identity and git availability.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.status",
        capability_id="repo.status",
        category="repository",
        description="Return summary-first repository status and cleanliness.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.branch.current",
        capability_id="repo.branch.current",
        category="repository",
        description="Return the active repository branch.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.branch.list",
        capability_id="repo.branch.list",
        category="repository",
        description="List local repository branches with summaries.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.history",
        capability_id="repo.history",
        category="repository",
        description="Return paginated recent commit summaries.",
        input_schema=_object_schema({
            "limit": _integer("Maximum commits to return."),
            "offset": _integer("Zero-based commit offset."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.repo.diff.summary",
        capability_id="repo.diff.summary",
        category="repository",
        description="Return changed-file and shortstat summaries without full diffs.",
        input_schema=_object_schema({}),
    ),
    MCPToolDefinition(
        name="ageix.repo.archive.create",
        capability_id="repo.archive.create",
        category="repository",
        description="Create a governed repository archive for selected paths or the whole repo with static exclusions.",
        input_schema=_object_schema({
            "paths": _array("Optional repo-relative paths to include. Omit for whole-repo snapshot."),
            "archive_name": _string("Optional archive file name."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.repo.archive.list",
        capability_id="repo.archive.list",
        category="repository",
        description="List governed repository archives.",
        input_schema=_object_schema({
            "limit": _integer("Maximum archives to return."),
            "offset": _integer("Zero-based archive offset."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.validation.profile.list",
        capability_id="validation.profile.list",
        category="validation",
        description="List approved validation profiles available for governed execution.",
        input_schema=_object_schema({
            "limit": _integer("Maximum profiles to return."),
            "offset": _integer("Zero-based profile offset."),
        }),
    ),
    MCPToolDefinition(
        name="ageix.validation.profile.get",
        capability_id="validation.profile.get",
        category="validation",
        description="Get an approved validation profile by ID.",
        input_schema=_object_schema({"profile_id": _string("Validation profile ID.")}, ["profile_id"]),
    ),
    MCPToolDefinition(
        name="ageix.validation.run.start",
        capability_id="validation.run.start",
        category="validation",
        description="Start an approved validation profile asynchronously. No arbitrary command input is accepted.",
        input_schema=_object_schema({"profile_id": _string("Validation profile ID to execute.")}, ["profile_id"]),
        recommended_next_tools=("ageix.validation.run.status", "ageix.validation.run.result"),
    ),
    MCPToolDefinition(
        name="ageix.validation.run.status",
        capability_id="validation.run.status",
        category="validation",
        description="Return summary-first status for an asynchronous validation run.",
        input_schema=_object_schema({"run_id": _string("Validation run ID.")}, ["run_id"]),
        recommended_next_tools=("ageix.validation.run.result",),
    ),
    MCPToolDefinition(
        name="ageix.validation.run.result",
        capability_id="validation.run.result",
        category="validation",
        description="Return validation run result, evidence package ID, and truncated output tails.",
        input_schema=_object_schema({"run_id": _string("Validation run ID.")}, ["run_id"]),
    ),
    MCPToolDefinition(
        name="ageix.validation.history",
        capability_id="validation.history",
        category="validation",
        description="List historical validation runs summary-first.",
        input_schema=_object_schema({
            "limit": _integer("Maximum runs to return."),
            "offset": _integer("Zero-based run offset."),
        }),
    ),


)
